/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_ERROR_MESSSAGE_CONST
{
	/// <summary>
	/// 服务器异常
	/// 显示类型:0
	/// </summary>
	public const int SERVER_ERROR = 1;
	/// <summary>
	/// 服务器id不存在
	/// 显示类型:0
	/// </summary>
	public const int SERVER_ID_NOT_EXISTS = 2;
	/// <summary>
	/// 请先登录帐号
	/// 显示类型:0
	/// </summary>
	public const int DO_NOT_LOGIN = 3;
	/// <summary>
	/// 服务器离线
	/// 显示类型:0
	/// </summary>
	public const int SERVER_IS_SHUTDOWN = 4;
	/// <summary>
	/// 用户名不能为空
	/// 显示类型:0
	/// </summary>
	public const int ACCOUNT_NAME_NULL = 5;
	/// <summary>
	/// 密码不能为空
	/// 显示类型:0
	/// </summary>
	public const int ACCOUNT_PASSWORD_NULL = 6;
	/// <summary>
	/// 用户名不存在
	/// 显示类型:0
	/// </summary>
	public const int ACCOUNT_NAME_NOT_EXISTS = 7;
	/// <summary>
	/// 密码不正确
	/// 显示类型:0
	/// </summary>
	public const int ACCOUNT_PASSWORD_NOT_CORRECT = 8;
	/// <summary>
	/// 邮箱不能为空
	/// 显示类型:0
	/// </summary>
	public const int ACCOUNT_EMAIL_NULL = 9;
	/// <summary>
	/// 用户名已存在
	/// 显示类型:0
	/// </summary>
	public const int ACCOUNT_NAME_IN_USE = 10;
	/// <summary>
	/// 邮箱格式错误
	/// 显示类型:0
	/// </summary>
	public const int ACCOUNT_EMAIL_ERROR = 11;
	/// <summary>
	/// 角色不存在
	/// 显示类型:0
	/// </summary>
	public const int ROLE_NOT_EXISTS = 12;
	/// <summary>
	/// 请先登录
	/// 显示类型:0
	/// </summary>
	public const int ACCOUNT_NULL = 13;
	/// <summary>
	/// 角色创建错误
	/// 显示类型:0
	/// </summary>
	public const int CREATE_ROLE_ERROR = 14;
	/// <summary>
	/// 该坦克没有主人
	/// 显示类型:0
	/// </summary>
	public const int ERROR_TANK_NO_OWNER = 15;
	/// <summary>
	/// 坦克经验不足
	/// 显示类型:0
	/// </summary>
	public const int ERROR_TANK_EXP_NOT_ENOUGH = 16;
	/// <summary>
	/// 错误的坦克模板id
	/// 显示类型:0
	/// </summary>
	public const int ERROR_TANK_TEMPLATE_ID = 17;
	/// <summary>
	/// 错误的坦克升星已满
	/// 显示类型:0
	/// </summary>
	public const int ERROR_TANK_QUALITY_MAX = 18;
	/// <summary>
	/// 坦克等级已满
	/// 显示类型:0
	/// </summary>
	public const int ERROR_TANK_LEVEL_MAX = 19;
	/// <summary>
	/// 配件类型与坦克不匹配
	/// 显示类型:0
	/// </summary>
	public const int ERROR_PART_SERIES_NOT_SUIT = 20;
	/// <summary>
	/// 错误的装备位
	/// 显示类型:0
	/// </summary>
	public const int ERROR_PLACE_EQUIP = 21;
	/// <summary>
	/// 装备的装备位不匹配
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EQUIPMENT_PLACE_NOT_SUIT = 22;
	/// <summary>
	/// 不存在该坦克
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_TANK = 23;
	/// <summary>
	/// 未知的升级类型
	/// 显示类型:0
	/// </summary>
	public const int ERROR_UNKNOW_UPGRADE_TYPE = 24;
	/// <summary>
	/// 坦克强化满级
	/// 显示类型:0
	/// </summary>
	public const int ERROR_TANK_STRENGTH_MAX = 25;
	/// <summary>
	/// 坦克强化规则错误
	/// 显示类型:0
	/// </summary>
	public const int ERROR_TANK_STRENGTH_RULE = 26;
	/// <summary>
	/// 不存在的坦克队伍
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_TANK_TEAM = 27;
	/// <summary>
	/// 位置错误
	/// 显示类型:0
	/// </summary>
	public const int ERROR_PLACE = 28;
	/// <summary>
	/// 坦克要交换的队伍重复
	/// 显示类型:0
	/// </summary>
	public const int ERROR_REPEATED_TEAM = 29;
	/// <summary>
	/// 金钱不足
	/// 显示类型:0
	/// </summary>
	public const int MONEY_NOT_ENOUGH = 30;
	/// <summary>
	/// 材料不足
	/// 显示类型:0
	/// </summary>
	public const int SUPPLIES_NOT_ENOUGH = 31;
	/// <summary>
	/// 物品不足
	/// 显示类型:0
	/// </summary>
	public const int PROPSES_NOT_ENOUGH = 32;
	/// <summary>
	/// 装备等级已经达到上限
	/// 显示类型:0
	/// </summary>
	public const int EQUIPMENT_LEVEL_MAX = 33;
	/// <summary>
	/// 装备经验不足
	/// 显示类型:0
	/// </summary>
	public const int EQUIPMENT_EXP_NOT_ENOUGHT = 34;
	/// <summary>
	/// 错误的装备模板id
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EQUIPMENT_TEMPLATE_ID = 35;
	/// <summary>
	/// 错误的装备升星id
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EQUIPMENT_CHANGE_ID = 36;
	/// <summary>
	/// 配件类型与坦克不匹配
	/// 显示类型:0
	/// </summary>
	public const int PART_SERIES_NOT_SUIT = 37;
	/// <summary>
	/// 配件槽位不存在
	/// 显示类型:0
	/// </summary>
	public const int PART_PART_NOT_EXISTS = 38;
	/// <summary>
	/// 没有对应的重铸附加属性
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_RECAST_ATTRIBUTES = 39;
	/// <summary>
	/// 没有对应的品质
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_RARE = 40;
	/// <summary>
	/// 没有对应的保留属性
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_SAVE_ATTRIBUTE = 41;
	/// <summary>
	/// 可重铸的属性为零
	/// 显示类型:0
	/// </summary>
	public const int ERROR_RECAST_ZERO = 42;
	/// <summary>
	/// 精炼达到上限
	/// 显示类型:0
	/// </summary>
	public const int ERROR_REFINING_LIMIT = 43;
	/// <summary>
	/// 精炼回退保留的属性过多
	/// 显示类型:0
	/// </summary>
	public const int ERROR_BACK_SAVE_MAX = 44;
	/// <summary>
	/// 没有可以回退的精炼属性
	/// 显示类型:0
	/// </summary>
	public const int ERROR_BACK_SIZE_ZERO = 45;
	/// <summary>
	/// 继承保留的属性过多
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EXTEND_SAVE_MAX = 46;
	/// <summary>
	/// 被继承的装备在坦克上
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EXTEND_ON_TANK = 47;
	/// <summary>
	/// 精炼的装备不能继承
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EXTEND_HAVE_REGINING = 48;
	/// <summary>
	/// 继承的部位不同
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EXTEND_SOLT_NOT_MATCH = 49;
	/// <summary>
	/// 装备不存在
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EQUIPMENT_NULL = 50;
	/// <summary>
	/// 装备没有可以保存的属性
	/// 显示类型:0
	/// </summary>
	public const int ERROR_EQUIPMENT_RECAST_BOOL = 51;
	/// <summary>
	/// 不存在的战役
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_CAMPAIGN = 52;
	/// <summary>
	/// 不存在的关卡
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_BATTLE = 53;
	/// <summary>
	/// 不存在的角色战役信息
	/// 显示类型:0
	/// </summary>
	public const int ERROR_ROLE_NO_CAMPAIGN = 54;
	/// <summary>
	/// 不存在的角色关卡信息
	/// 显示类型:0
	/// </summary>
	public const int ERROR_ROLE_NO_BATTLE = 55;
	/// <summary>
	/// 可以战斗的次数为零
	/// 显示类型:0
	/// </summary>
	public const int ERROR_BATTLE_COUNT_ZERO = 56;
	/// <summary>
	/// 前置关卡没完成
	/// 显示类型:0
	/// </summary>
	public const int ERROR_PREVIOUS_NULL = 57;
	/// <summary>
	/// 子关卡没完成
	/// 显示类型:0
	/// </summary>
	public const int ERROR_CHILDREN_NULL = 58;
	/// <summary>
	/// 奖励不存在
	/// 显示类型:0
	/// </summary>
	public const int ERROR_REWARD_NULL = 59;
	/// <summary>
	/// npc坦克不存在
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NPC_TANK_NULL = 60;
	/// <summary>
	/// 掉落不存在
	/// 显示类型:0
	/// </summary>
	public const int ERROR_DROP_NULL = 61;
	/// <summary>
	/// 零件等级已经达到上限
	/// 显示类型:0
	/// </summary>
	public const int PART_LEVEL_MAX = 62;
	/// <summary>
	/// 零件经验不足
	/// 显示类型:0
	/// </summary>
	public const int PART_EXP_NOT_ENOUGHT = 63;
	/// <summary>
	/// 不存在该坦克
	/// 显示类型:0
	/// </summary>
	public const int DO_NOT_HAVE_TANK = 64;
	/// <summary>
	/// 不存在该装备
	/// 显示类型:0
	/// </summary>
	public const int DO_NOT_HAVE_EQUIPMENT = 65;
	/// <summary>
	/// 不存在该零件
	/// 显示类型:0
	/// </summary>
	public const int DO_NOT_HAVE_PART = 66;
	/// <summary>
	/// 不存在该乘员
	/// 显示类型:0
	/// </summary>
	public const int DO_NOT_HAVE_DRIVER = 67;
	/// <summary>
	/// 升级条件不足
	/// 显示类型:0
	/// </summary>
	public const int ERROR_UPGRADE_NOT_ENOUGH = 68;
	/// <summary>
	/// 强化条件不足
	/// 显示类型:0
	/// </summary>
	public const int ERROR_STRENGHT_NOT_ENOUGH = 69;
	/// <summary>
	/// 改造条件不足
	/// 显示类型:0
	/// </summary>
	public const int ERROR_REFORME_NOT_ENOUGH = 70;
	/// <summary>
	/// 客户端版本不是最新的
	/// 显示类型:0
	/// </summary>
	public const int ERRO_NOT_NEW_CLIENT = 71;
	/// <summary>
	/// 角色名称重复
	/// 显示类型:0
	/// </summary>
	public const int ERROR_REPEAT_NAME = 72;
	/// <summary>
	/// 角色名称违法
	/// 显示类型:0
	/// </summary>
	public const int ERROR_FORBID_NAME = 73;
	/// <summary>
	/// 错误的服务器连接
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_PROCCESS = 74;
	/// <summary>
	/// 不存在此角色的竞技场数据
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_ARENAINFO = 75;
	/// <summary>
	/// 不存在的竞技场战斗信息
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_ARENADATA = 76;
	/// <summary>
	/// 当前等级不足
	/// 显示类型:0
	/// </summary>
	public const int ERROR_LEVEL_NOT_ENOUGH = 77;
	/// <summary>
	/// 没有满足条件的对手
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_RANDOM_DATA = 78;
	/// <summary>
	/// 当前挑战次数为0，无法进行挑战
	/// 显示类型:0
	/// </summary>
	public const int ERROR_COUNT_NOT_ENOUGH = 79;
	/// <summary>
	/// 已领取过奖励
	/// 显示类型:0
	/// </summary>
	public const int ERROR_RECEIVE_REWARD = 80;
	/// <summary>
	/// 星星数量不够
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NOT_ENOUGH_STAR = 81;
	/// <summary>
	/// 重复登录帐号
	/// 显示类型:0
	/// </summary>
	public const int DO_REPEAT_LOGIN = 82;
	/// <summary>
	/// 不存在的每日签到数据
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_SIGN_DAILY = 83;
	/// <summary>
	/// 不存在的签到宝箱
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_SIGN_BOX = 84;
	/// <summary>
	/// 签到天数错误
	/// 显示类型:0
	/// </summary>
	public const int ERROR_SIGN_DAY = 85;
	/// <summary>
	/// 签到天数不够
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NOT_ENOUGH_DAYS = 86;
	/// <summary>
	/// 已领取过宝箱
	/// 显示类型:0
	/// </summary>
	public const int ERROR_GET_BOX = 87;
	/// <summary>
	/// 腾讯登录错误
	/// 显示类型:0
	/// </summary>
	public const int ERROR_TENCENT_LOGIN = 88;
	/// <summary>
	/// 服务器登录错误
	/// 显示类型:0
	/// </summary>
	public const int ERROR_SERVER_LOGIN = 89;
	/// <summary>
	/// MD5错误
	/// 显示类型:1
	/// </summary>
	public const int ERROR_MD5 = 90;
	/// <summary>
	/// 不存在活动数据
	/// 显示类型:0
	/// </summary>
	public const int ERROR_ACTIVITY_DATA_NULL = 91;
	/// <summary>
	/// 未达到领奖条件
	/// 显示类型:0
	/// </summary>
	public const int ERROR_OPER_NOT_COMPLETE = 92;
	/// <summary>
	/// 战略大作战探索次数不足
	/// 显示类型:0
	/// </summary>
	public const int ERROR_ZLDZZ_EXPLORE_COUNT = 93;
	/// <summary>
	/// 此关卡不能扫荡
	/// 显示类型:0
	/// </summary>
	public const int ERROR_CANNOT_SWEEP = 94;
	/// <summary>
	/// 三星通关才能扫荡
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NEED_3STAR = 95;
	/// <summary>
	/// 不存在超时数据
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_TIMEOUT = 96;
	/// <summary>
	/// 今日购买次数已用完
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NOT_ENOUGH_BUYTIMES = 97;
	/// <summary>
	/// 新手流程不匹配
	/// 显示类型:0
	/// </summary>
	public const int ERROR_GUIDE_STEP = 98;
	/// <summary>
	/// 奖励已过期
	/// 显示类型:0
	/// </summary>
	public const int ERROR_REWARD_TIMEOUT = 99;
	/// <summary>
	/// 奖励被领完了
	/// 显示类型:0
	/// </summary>
	public const int ERROR_REWARD_NOT_ENOUGH = 100;
	/// <summary>
	/// 不存在的福利或活动数据
	/// 显示类型:0
	/// </summary>
	public const int ERROR_NO_OPER_CONTENT = 101;
}
