using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Airport : IDB_BaseInt
{
	const string SQL = @"select _index, id, difficulty, tankcenter_id, refresh_npc1_id, refresh_time1, refresh_max1, refresh_npc2_id, refresh_time2, refresh_max2, airspeed1, airspeed2, mesh1_name, mesh2_name, limit_time, qualification from conf_airport";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///关卡ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///关卡难度
	/// </summary>
	public int Difficulty { get; set; }
	/// <summary>
	///坦克指挥中心ID
	/// </summary>
	public int Tankcenter_id { get; set; }
	/// <summary>
	///坦克刷新NPCID
	/// </summary>
	public int Refresh_npc1_id { get; set; }
	/// <summary>
	///坦克刷新间隔
	/// </summary>
	public int Refresh_time1 { get; set; }
	/// <summary>
	///坦克刷新限制
	/// </summary>
	public int Refresh_max1 { get; set; }
	/// <summary>
	///飞机刷新NPCID
	/// </summary>
	public int Refresh_npc2_id { get; set; }
	/// <summary>
	///飞机刷新间隔
	/// </summary>
	public int Refresh_time2 { get; set; }
	/// <summary>
	///飞机刷新限制
	/// </summary>
	public int Refresh_max2 { get; set; }
	/// <summary>
	///飞机滑行速度
	/// </summary>
	public int Airspeed1 { get; set; }
	/// <summary>
	///飞机滑行速度
	/// </summary>
	public int Airspeed2 { get; set; }
	/// <summary>
	///飞机存活模型ID
	/// </summary>
	public string Mesh1_name { get; set; }
	/// <summary>
	///飞机死亡模型ID
	/// </summary>
	public string Mesh2_name { get; set; }
	/// <summary>
	///限制时间
	/// </summary>
	public int Limit_time { get; set; }
	/// <summary>
	///击杀数量
	/// </summary>
	public int Qualification { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Airport module = new DB_Airport()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Difficulty		 = reader.GetInt32(2),
					Tankcenter_id		 = reader.GetInt32(3),
					Refresh_npc1_id		 = reader.GetInt32(4),
					Refresh_time1		 = reader.GetInt32(5),
					Refresh_max1		 = reader.GetInt32(6),
					Refresh_npc2_id		 = reader.GetInt32(7),
					Refresh_time2		 = reader.GetInt32(8),
					Refresh_max2		 = reader.GetInt32(9),
					Airspeed1		 = reader.GetInt32(10),
					Airspeed2		 = reader.GetInt32(11),
					Mesh1_name		 = reader.GetString(12),
					Mesh2_name		 = reader.GetString(13),
					Limit_time		 = reader.GetInt32(14),
					Qualification		 = reader.GetInt32(15),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
