using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Activities_battle : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, type, type_name, before_battle_text, loadingtips, introduction, description, enemy_commander_show, enemy_show, prop_show, consume, reward, drop1_id, drop2_id, drop3_id, drop4_id, drop5_id, limit_count, map, priority, player_load_pos, signs, time_limit, follow_npc from conf_activities_battle";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///关卡ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///关卡名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///关卡类型
	/// </summary>
	public int Type { get; set; }
	/// <summary>
	///关卡类型名称
	/// </summary>
	public string Type_name { get; set; }
	/// <summary>
	///战前特效文字
	/// </summary>
	public string Before_battle_text { get; set; }
	/// <summary>
	///loading简介
	/// </summary>
	public string Loadingtips { get; set; }
	/// <summary>
	///关卡介绍
	/// </summary>
	public string Introduction { get; set; }
	/// <summary>
	///战役目标
	/// </summary>
	public string Description { get; set; }
	/// <summary>
	///敌军指挥官展示。此列填写指挥官id，客户端需要根据指挥官id在conf_commander_attr找到对应的图片显示
	/// </summary>
	public int Enemy_commander_show { get; set; }
	/// <summary>
	///敌军展示.此列填写坦克id。客户端需要从conf_npc_tank中读取对应的坦克图片
	/// </summary>
	public string Enemy_show { get; set; }
	/// <summary>
	///掉落展示
	/// </summary>
	public int Prop_show { get; set; }
	/// <summary>
	///消耗组
	/// </summary>
	public int Consume { get; set; }
	/// <summary>
	///奖励组
	/// </summary>
	public int Reward { get; set; }
	/// <summary>
	///掉落组ID1
	/// </summary>
	public int Drop1_id { get; set; }
	/// <summary>
	///掉落组ID2
	/// </summary>
	public int Drop2_id { get; set; }
	/// <summary>
	///掉落组ID3
	/// </summary>
	public int Drop3_id { get; set; }
	/// <summary>
	///掉落组ID4
	/// </summary>
	public int Drop4_id { get; set; }
	/// <summary>
	///掉落组ID5
	/// </summary>
	public int Drop5_id { get; set; }
	/// <summary>
	///挑战次数限制
	/// </summary>
	public int Limit_count { get; set; }
	/// <summary>
	///地图
	/// </summary>
	public string Map { get; set; }
	/// <summary>
	///优先级
	/// </summary>
	public int Priority { get; set; }
	/// <summary>
	///玩家加载位置
	/// </summary>
	public string Player_load_pos { get; set; }
	/// <summary>
	///导航点列表
	/// </summary>
	public string Signs { get; set; }
	/// <summary>
	///时间限制
	/// </summary>
	public float Time_limit { get; set; }
	/// <summary>
	///跟随NPC
	/// </summary>
	public int Follow_npc { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Activities_battle module = new DB_Activities_battle()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Type		 = reader.GetInt32(3),
					Type_name		 = reader.GetString(4),
					Before_battle_text		 = reader.GetString(5),
					Loadingtips		 = reader.GetString(6),
					Introduction		 = reader.GetString(7),
					Description		 = reader.GetString(8),
					Enemy_commander_show		 = reader.GetInt32(9),
					Enemy_show		 = reader.GetString(10),
					Prop_show		 = reader.GetInt32(11),
					Consume		 = reader.GetInt32(12),
					Reward		 = reader.GetInt32(13),
					Drop1_id		 = reader.GetInt32(14),
					Drop2_id		 = reader.GetInt32(15),
					Drop3_id		 = reader.GetInt32(16),
					Drop4_id		 = reader.GetInt32(17),
					Drop5_id		 = reader.GetInt32(18),
					Limit_count		 = reader.GetInt32(19),
					Map		 = reader.GetString(20),
					Priority		 = reader.GetInt32(21),
					Player_load_pos		 = reader.GetString(22),
					Signs		 = reader.GetString(23),
					Time_limit		 = reader.GetFloat(24),
					Follow_npc		 = reader.GetInt32(25),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
