using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Alamein_event_tag : IDB_BaseInt
{
	const string SQL = @"select _index, battle_type_id, comment, open_time, cd_increased, cd_limit, type_name, battle_id, unlock_level, reward_icon, reward_info, open_txt from conf_alamein_event_tag";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///战斗类型id
	/// </summary>
	public int Battle_type_id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///开放时间
	/// </summary>
	public string Open_time { get; set; }
	/// <summary>
	///战斗增加cd
	/// </summary>
	public int Cd_increased { get; set; }
	/// <summary>
	///CD上限
	/// </summary>
	public int Cd_limit { get; set; }
	/// <summary>
	///类型名称
	/// </summary>
	public string Type_name { get; set; }
	/// <summary>
	///关卡id
	/// </summary>
	public string Battle_id { get; set; }
	/// <summary>
	///解锁等级
	/// </summary>
	public int Unlock_level { get; set; }
	/// <summary>
	///奖励图标
	/// </summary>
	public int Reward_icon { get; set; }
	/// <summary>
	///奖励文字
	/// </summary>
	public string Reward_info { get; set; }
	/// <summary>
	///开启时间日期
	/// </summary>
	public string Open_txt { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Alamein_event_tag module = new DB_Alamein_event_tag()
				{
					_index		 = reader.GetInt32(0),
					Battle_type_id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Open_time		 = reader.GetString(3),
					Cd_increased		 = reader.GetInt32(4),
					Cd_limit		 = reader.GetInt32(5),
					Type_name		 = reader.GetString(6),
					Battle_id		 = reader.GetString(7),
					Unlock_level		 = reader.GetInt32(8),
					Reward_icon		 = reader.GetInt32(9),
					Reward_info		 = reader.GetString(10),
					Open_txt		 = reader.GetString(11),
				};
				tmp.Add(module.Battle_type_id, module);
			}
		});
		return tmp;
	}
}
