using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Attr_explan : IDB_BaseInt
{
	const string SQL = @"select _index, id, attr, data_type, comment, attr_Icon from conf_attr_explan";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///属性ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///属性
	/// </summary>
	public string Attr { get; set; }
	/// <summary>
	///数据类型
	/// </summary>
	public string Data_type { get; set; }
	/// <summary>
	///属性描述
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///属性图标
	/// </summary>
	public int Attr_Icon { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Attr_explan module = new DB_Attr_explan()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Attr		 = reader.GetString(2),
					Data_type		 = reader.GetString(3),
					Comment		 = reader.GetString(4),
					Attr_Icon		 = reader.GetInt32(5),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
