using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Activities_npc_center : IDB_BaseInt
{
	const string SQL = @"select _index, id, load_pos, formation_name, tank_list, type, load_delayed from conf_activities_npc_center";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///指挥中心ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///加载位置
	/// </summary>
	public string Load_pos { get; set; }
	/// <summary>
	///指挥中心阵型名
	/// </summary>
	public string Formation_name { get; set; }
	/// <summary>
	///坦克列表
	/// </summary>
	public string Tank_list { get; set; }
	/// <summary>
	///行为类型
	/// </summary>
	public int Type { get; set; }
	/// <summary>
	///加载延时
	/// </summary>
	public float Load_delayed { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Activities_npc_center module = new DB_Activities_npc_center()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Load_pos		 = reader.GetString(2),
					Formation_name		 = reader.GetString(3),
					Tank_list		 = reader.GetString(4),
					Type		 = reader.GetInt32(5),
					Load_delayed		 = reader.GetFloat(6),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
