using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Activities_player_center : IDB_BaseInt
{
	const string SQL = @"select _index, id, battle_id, battle_order, flag_key, scenes, is_default, type, center_list, is_succeed, succeed_condition_type, succeed_param, description from conf_activities_player_center";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///行为ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///战斗ID
	/// </summary>
	public int Battle_id { get; set; }
	/// <summary>
	///战斗顺序
	/// </summary>
	public int Battle_order { get; set; }
	/// <summary>
	///旗子ID
	/// </summary>
	public string Flag_key { get; set; }
	/// <summary>
	///旗子所在场景
	/// </summary>
	public string Scenes { get; set; }
	/// <summary>
	///是否默认
	/// </summary>
	public int Is_default { get; set; }
	/// <summary>
	///行为类型
	/// </summary>
	public int Type { get; set; }
	/// <summary>
	///指挥中心列表
	/// </summary>
	public string Center_list { get; set; }
	/// <summary>
	///是否为总胜利条件
	/// </summary>
	public int Is_succeed { get; set; }
	/// <summary>
	///行为胜利条件
	/// </summary>
	public int Succeed_condition_type { get; set; }
	/// <summary>
	///行为胜利参数
	/// </summary>
	public float Succeed_param { get; set; }
	/// <summary>
	///任务说明
	/// </summary>
	public string Description { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Activities_player_center module = new DB_Activities_player_center()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Battle_id		 = reader.GetInt32(2),
					Battle_order		 = reader.GetInt32(3),
					Flag_key		 = reader.GetString(4),
					Scenes		 = reader.GetString(5),
					Is_default		 = reader.GetInt32(6),
					Type		 = reader.GetInt32(7),
					Center_list		 = reader.GetString(8),
					Is_succeed		 = reader.GetInt32(9),
					Succeed_condition_type		 = reader.GetInt32(10),
					Succeed_param		 = reader.GetFloat(11),
					Description		 = reader.GetString(12),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
