using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Battle_behavior : IDB_BaseInt
{
	const string SQL = @"select _index, id, battle_id, battle_order, is_select_tactics, enemy_commander_action_type, other_support, before_battle_text, init_look_pos, player_load_pos, select_tactics_pos, player_battle_pos, look_pos, enemy_battle_pos, enemy_load_pos, enemy_support_load_pos, signs, enemy_center_path, enemy_tank_list, enemy_support_tank_list, is_succeed, succeed_condition_type, succeed_param, animation_path, animation_delay, pre_dialog, fol_dialog, description, tactic_notice_text, Camera_drag, Camera_speed from conf_battle_behavior";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///行为ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///关卡ID
	/// </summary>
	public int Battle_id { get; set; }
	/// <summary>
	///战斗顺序
	/// </summary>
	public int Battle_order { get; set; }
	/// <summary>
	///是否选择战术
	/// </summary>
	public int Is_select_tactics { get; set; }
	/// <summary>
	///敌方指挥官技能释放（1自动释放根据cd，2进入战斗时释放一次）
	/// </summary>
	public int Enemy_commander_action_type { get; set; }
	/// <summary>
	///是否侧面支援
	/// </summary>
	public int Other_support { get; set; }
	/// <summary>
	///战前特效文字
	/// </summary>
	public string Before_battle_text { get; set; }
	/// <summary>
	///摄像机初始点
	/// </summary>
	public string Init_look_pos { get; set; }
	/// <summary>
	///玩家加载点
	/// </summary>
	public string Player_load_pos { get; set; }
	/// <summary>
	///战术选择点
	/// </summary>
	public string Select_tactics_pos { get; set; }
	/// <summary>
	///玩家战斗点
	/// </summary>
	public string Player_battle_pos { get; set; }
	/// <summary>
	///摄像机观察点
	/// </summary>
	public string Look_pos { get; set; }
	/// <summary>
	///敌人战斗点
	/// </summary>
	public string Enemy_battle_pos { get; set; }
	/// <summary>
	///敌人加载点
	/// </summary>
	public string Enemy_load_pos { get; set; }
	/// <summary>
	///敌人支援加载点
	/// </summary>
	public string Enemy_support_load_pos { get; set; }
	/// <summary>
	///导航点列表
	/// </summary>
	public string Signs { get; set; }
	/// <summary>
	///敌人阵型预设加载路径
	/// </summary>
	public string Enemy_center_path { get; set; }
	/// <summary>
	///敌人坦克列表
	/// </summary>
	public string Enemy_tank_list { get; set; }
	/// <summary>
	///敌人支援坦克列表
	/// </summary>
	public string Enemy_support_tank_list { get; set; }
	/// <summary>
	///是否为总胜利条件
	/// </summary>
	public int Is_succeed { get; set; }
	/// <summary>
	///行为胜利条件
	/// </summary>
	public int Succeed_condition_type { get; set; }
	/// <summary>
	///行为胜利参数
	/// </summary>
	public float Succeed_param { get; set; }
	/// <summary>
	///动画路径
	/// </summary>
	public string Animation_path { get; set; }
	/// <summary>
	///动画播放延迟
	/// </summary>
	public float Animation_delay { get; set; }
	/// <summary>
	///战前对话
	/// </summary>
	public int Pre_dialog { get; set; }
	/// <summary>
	///战后对话
	/// </summary>
	public int Fol_dialog { get; set; }
	/// <summary>
	///任务说明
	/// </summary>
	public string Description { get; set; }
	/// <summary>
	///战术提示文本
	/// </summary>
	public string Tactic_notice_text { get; set; }
	/// <summary>
	///摄像机拖动范围
	/// </summary>
	public string Camera_drag { get; set; }
	/// <summary>
	///Lookpoint点间镜头移动速度
	/// </summary>
	public float Camera_speed { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Battle_behavior module = new DB_Battle_behavior()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Battle_id		 = reader.GetInt32(2),
					Battle_order		 = reader.GetInt32(3),
					Is_select_tactics		 = reader.GetInt32(4),
					Enemy_commander_action_type		 = reader.GetInt32(5),
					Other_support		 = reader.GetInt32(6),
					Before_battle_text		 = reader.GetString(7),
					Init_look_pos		 = reader.GetString(8),
					Player_load_pos		 = reader.GetString(9),
					Select_tactics_pos		 = reader.GetString(10),
					Player_battle_pos		 = reader.GetString(11),
					Look_pos		 = reader.GetString(12),
					Enemy_battle_pos		 = reader.GetString(13),
					Enemy_load_pos		 = reader.GetString(14),
					Enemy_support_load_pos		 = reader.GetString(15),
					Signs		 = reader.GetString(16),
					Enemy_center_path		 = reader.GetString(17),
					Enemy_tank_list		 = reader.GetString(18),
					Enemy_support_tank_list		 = reader.GetString(19),
					Is_succeed		 = reader.GetInt32(20),
					Succeed_condition_type		 = reader.GetInt32(21),
					Succeed_param		 = reader.GetFloat(22),
					Animation_path		 = reader.GetString(23),
					Animation_delay		 = reader.GetFloat(24),
					Pre_dialog		 = reader.GetInt32(25),
					Fol_dialog		 = reader.GetInt32(26),
					Description		 = reader.GetString(27),
					Tactic_notice_text		 = reader.GetString(28),
					Camera_drag		 = reader.GetString(29),
					Camera_speed		 = reader.GetFloat(30),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
