using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Breakout_event : IDB_BaseInt
{
	const string SQL = @"select _index, event_id, comment, event_battle_id, next_event_id, battle_icon, vest_score_reward, pos, back_star, icon_star, back_end, icon_end, breakout_reward from conf_breakout_event";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///事件ID
	/// </summary>
	public int Event_id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///战场ID
	/// </summary>
	public int Event_battle_id { get; set; }
	/// <summary>
	///下一关
	/// </summary>
	public int Next_event_id { get; set; }
	/// <summary>
	///关卡类型
	/// </summary>
	public int Battle_icon { get; set; }
	/// <summary>
	///最高成绩奖励
	/// </summary>
	public int Vest_score_reward { get; set; }
	/// <summary>
	///坐标
	/// </summary>
	public string Pos { get; set; }
	/// <summary>
	///初始底板
	/// </summary>
	public int Back_star { get; set; }
	/// <summary>
	///初始图标
	/// </summary>
	public int Icon_star { get; set; }
	/// <summary>
	///击杀底板
	/// </summary>
	public int Back_end { get; set; }
	/// <summary>
	///击杀图标
	/// </summary>
	public int Icon_end { get; set; }
	/// <summary>
	///扫荡奖励组
	/// </summary>
	public int Breakout_reward { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Breakout_event module = new DB_Breakout_event()
				{
					_index		 = reader.GetInt32(0),
					Event_id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Event_battle_id		 = reader.GetInt32(3),
					Next_event_id		 = reader.GetInt32(4),
					Battle_icon		 = reader.GetInt32(5),
					Vest_score_reward		 = reader.GetInt32(6),
					Pos		 = reader.GetString(7),
					Back_star		 = reader.GetInt32(8),
					Icon_star		 = reader.GetInt32(9),
					Back_end		 = reader.GetInt32(10),
					Icon_end		 = reader.GetInt32(11),
					Breakout_reward		 = reader.GetInt32(12),
				};
				tmp.Add(module.Event_id, module);
			}
		});
		return tmp;
	}
}
