using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Battle_other_support : IDB_BaseInt
{
	const string SQL = @"select _index, id, enemy_battle_pos, enemy_load_pos, enemy_support_load_pos, enemy_center_path, enemy_tank_list, enemy_support_tank_list from conf_battle_other_support";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///行为ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///敌人战斗点
	/// </summary>
	public string Enemy_battle_pos { get; set; }
	/// <summary>
	///敌人加载点
	/// </summary>
	public string Enemy_load_pos { get; set; }
	/// <summary>
	///敌人支援加载点
	/// </summary>
	public string Enemy_support_load_pos { get; set; }
	/// <summary>
	///敌人阵型预设加载路径
	/// </summary>
	public string Enemy_center_path { get; set; }
	/// <summary>
	///敌人坦克列表
	/// </summary>
	public string Enemy_tank_list { get; set; }
	/// <summary>
	///敌人支援坦克列表
	/// </summary>
	public string Enemy_support_tank_list { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Battle_other_support module = new DB_Battle_other_support()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Enemy_battle_pos		 = reader.GetString(2),
					Enemy_load_pos		 = reader.GetString(3),
					Enemy_support_load_pos		 = reader.GetString(4),
					Enemy_center_path		 = reader.GetString(5),
					Enemy_tank_list		 = reader.GetString(6),
					Enemy_support_tank_list		 = reader.GetString(7),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
