using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Battleground : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, comment, pre_id, background_pic1, background_pic2, background_pic3, background_pic4, background_pic5, background_pic6, background_pic7, background_pic8, background_pic9, background_pic10, background_pic11, background_pic12, campaign_line_prefab from conf_battleground";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///战区ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///战区名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///战役备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///前置战区ID
	/// </summary>
	public int Pre_id { get; set; }
	/// <summary>
	///背景图1
	/// </summary>
	public int Background_pic1 { get; set; }
	/// <summary>
	///背景图2
	/// </summary>
	public int Background_pic2 { get; set; }
	/// <summary>
	///背景图3
	/// </summary>
	public int Background_pic3 { get; set; }
	/// <summary>
	///背景图4
	/// </summary>
	public int Background_pic4 { get; set; }
	/// <summary>
	///背景图5
	/// </summary>
	public int Background_pic5 { get; set; }
	/// <summary>
	///背景图6
	/// </summary>
	public int Background_pic6 { get; set; }
	/// <summary>
	///背景图7
	/// </summary>
	public int Background_pic7 { get; set; }
	/// <summary>
	///背景图8
	/// </summary>
	public int Background_pic8 { get; set; }
	/// <summary>
	///背景图9
	/// </summary>
	public int Background_pic9 { get; set; }
	/// <summary>
	///背景图10
	/// </summary>
	public int Background_pic10 { get; set; }
	/// <summary>
	///背景图11
	/// </summary>
	public int Background_pic11 { get; set; }
	/// <summary>
	///背景图12
	/// </summary>
	public int Background_pic12 { get; set; }
	/// <summary>
	///战役轮廓线预设
	/// </summary>
	public string Campaign_line_prefab { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Battleground module = new DB_Battleground()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Comment		 = reader.GetString(3),
					Pre_id		 = reader.GetInt32(4),
					Background_pic1		 = reader.GetInt32(5),
					Background_pic2		 = reader.GetInt32(6),
					Background_pic3		 = reader.GetInt32(7),
					Background_pic4		 = reader.GetInt32(8),
					Background_pic5		 = reader.GetInt32(9),
					Background_pic6		 = reader.GetInt32(10),
					Background_pic7		 = reader.GetInt32(11),
					Background_pic8		 = reader.GetInt32(12),
					Background_pic9		 = reader.GetInt32(13),
					Background_pic10		 = reader.GetInt32(14),
					Background_pic11		 = reader.GetInt32(15),
					Background_pic12		 = reader.GetInt32(16),
					Campaign_line_prefab		 = reader.GetString(17),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
