using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Blueprint_build : IDB_BaseInt
{
	const string SQL = @"select _index, orderid, comment, gettankid, Id, money_cost, cost1_type, cost1_id, material1cost, cost2_type, cost2_id, material2cost, cost3_type, cost3_id, material3cost, cost4_type, cost4_id, material4cost, description1, num1, description2, num2, description3, num3, description4, num4 from conf_blueprint_build";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///图纸排序
	/// </summary>
	public int Orderid { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///获得坦克id
	/// </summary>
	public int Gettankid { get; set; }
	/// <summary>
	///图纸id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///消耗金钱
	/// </summary>
	public int Money_cost { get; set; }
	/// <summary>
	///消耗1类型
	/// </summary>
	public int Cost1_type { get; set; }
	/// <summary>
	///消耗1id
	/// </summary>
	public int Cost1_id { get; set; }
	/// <summary>
	///消耗1001数量
	/// </summary>
	public int Material1cost { get; set; }
	/// <summary>
	///消耗2类型
	/// </summary>
	public int Cost2_type { get; set; }
	/// <summary>
	///消耗2id
	/// </summary>
	public int Cost2_id { get; set; }
	/// <summary>
	///消耗1002数量
	/// </summary>
	public int Material2cost { get; set; }
	/// <summary>
	///消耗3类型
	/// </summary>
	public int Cost3_type { get; set; }
	/// <summary>
	///消耗3id
	/// </summary>
	public int Cost3_id { get; set; }
	/// <summary>
	///消耗1003数量
	/// </summary>
	public int Material3cost { get; set; }
	/// <summary>
	///消耗4类型
	/// </summary>
	public int Cost4_type { get; set; }
	/// <summary>
	///消耗4id
	/// </summary>
	public int Cost4_id { get; set; }
	/// <summary>
	///消耗1004数量
	/// </summary>
	public int Material4cost { get; set; }
	/// <summary>
	///左上描述文字
	/// </summary>
	public string Description1 { get; set; }
	/// <summary>
	///左上描述数字
	/// </summary>
	public int Num1 { get; set; }
	/// <summary>
	///右上描述文字
	/// </summary>
	public string Description2 { get; set; }
	/// <summary>
	///右上描述数字
	/// </summary>
	public int Num2 { get; set; }
	/// <summary>
	///左下描述文字
	/// </summary>
	public string Description3 { get; set; }
	/// <summary>
	///左下描述数字
	/// </summary>
	public int Num3 { get; set; }
	/// <summary>
	///右下描述文字
	/// </summary>
	public string Description4 { get; set; }
	/// <summary>
	///右下描述数字
	/// </summary>
	public int Num4 { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Blueprint_build module = new DB_Blueprint_build()
				{
					_index		 = reader.GetInt32(0),
					Orderid		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Gettankid		 = reader.GetInt32(3),
					Id		 = reader.GetInt32(4),
					Money_cost		 = reader.GetInt32(5),
					Cost1_type		 = reader.GetInt32(6),
					Cost1_id		 = reader.GetInt32(7),
					Material1cost		 = reader.GetInt32(8),
					Cost2_type		 = reader.GetInt32(9),
					Cost2_id		 = reader.GetInt32(10),
					Material2cost		 = reader.GetInt32(11),
					Cost3_type		 = reader.GetInt32(12),
					Cost3_id		 = reader.GetInt32(13),
					Material3cost		 = reader.GetInt32(14),
					Cost4_type		 = reader.GetInt32(15),
					Cost4_id		 = reader.GetInt32(16),
					Material4cost		 = reader.GetInt32(17),
					Description1		 = reader.GetString(18),
					Num1		 = reader.GetInt32(19),
					Description2		 = reader.GetString(20),
					Num2		 = reader.GetInt32(21),
					Description3		 = reader.GetString(22),
					Num3		 = reader.GetInt32(23),
					Description4		 = reader.GetString(24),
					Num4		 = reader.GetInt32(25),
				};
				tmp.Add(module.Orderid, module);
			}
		});
		return tmp;
	}
}
