using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Button_lock : IDB_BaseInt
{
	const string SQL = @"select _index, id, lock_tip_info, mission_id, lock_show_type from conf_button_lock";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///解锁项目id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///锁住的提示面板信息
	/// </summary>
	public string Lock_tip_info { get; set; }
	/// <summary>
	///任务id
	/// </summary>
	public string Mission_id { get; set; }
	/// <summary>
	///锁住的表现（1.主界面隐藏。2是车库界面加锁。3是战役失败加锁
	/// </summary>
	public int Lock_show_type { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Button_lock module = new DB_Button_lock()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Lock_tip_info		 = reader.GetString(2),
					Mission_id		 = reader.GetString(3),
					Lock_show_type		 = reader.GetInt32(4),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
