using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Battle_ui_pos : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, pos, ui_res, link_line_pos, link_line_path from conf_battle_ui_pos";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///关卡ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///类型简介
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///坐标
	/// </summary>
	public string Pos { get; set; }
	/// <summary>
	///关卡图标
	/// </summary>
	public int Ui_res { get; set; }
	/// <summary>
	///坐标线
	/// </summary>
	public string Link_line_pos { get; set; }
	/// <summary>
	///线路经
	/// </summary>
	public string Link_line_path { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Battle_ui_pos module = new DB_Battle_ui_pos()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Pos		 = reader.GetString(3),
					Ui_res		 = reader.GetInt32(4),
					Link_line_pos		 = reader.GetString(5),
					Link_line_path		 = reader.GetString(6),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
