using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Commander_level : IDB_BaseInt
{
	const string SQL = @"select _index, Commander_Rank_level, Comment, Exp_For_Next_Level, Exp_For_Current_Level from conf_commander_level";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///指挥官军衔等级
	/// </summary>
	public int Commander_Rank_level { get; set; }
	/// <summary>
	///开放备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///到下一集所需经验
	/// </summary>
	public int Exp_For_Next_Level { get; set; }
	/// <summary>
	///当前级别所需总经验
	/// </summary>
	public int Exp_For_Current_Level { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Commander_level module = new DB_Commander_level()
				{
					_index		 = reader.GetInt32(0),
					Commander_Rank_level		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Exp_For_Next_Level		 = reader.GetInt32(3),
					Exp_For_Current_Level		 = reader.GetInt32(4),
				};
				tmp.Add(module.Commander_Rank_level, module);
			}
		});
		return tmp;
	}
}
