using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Campaign : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, chapter, unlocklevel, comment, pre_id, max_battle, battleground_id, prefab_name, shining_material, background_pic1, background_pic2, background_pic3, background_pic4, background_pic5, background_pic6, background_pic7, background_pic8, background_pic9, background_pic10, background_pic11, background_pic12, normal_star_level1, normal_star_level2, normal_star_level3, normal_level1_coinnum, normal_level2_coinnum, normal_level3_coinnum, elite_star_level1, elite_star_level2, elite_star_level3, elite_level1_coinnum, elite_level2_coinnum, elite_level3_coinnum from conf_campaign";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///战役ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///战役名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///战役章节
	/// </summary>
	public string Chapter { get; set; }
	/// <summary>
	///解锁等级
	/// </summary>
	public int Unlocklevel { get; set; }
	/// <summary>
	///战役备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///前置战役
	/// </summary>
	public int Pre_id { get; set; }
	/// <summary>
	///同时开启战斗数
	/// </summary>
	public int Max_battle { get; set; }
	/// <summary>
	///归属战区
	/// </summary>
	public int Battleground_id { get; set; }
	/// <summary>
	///战区预设
	/// </summary>
	public string Prefab_name { get; set; }
	/// <summary>
	///扫光特效
	/// </summary>
	public string Shining_material { get; set; }
	/// <summary>
	///背景图1
	/// </summary>
	public int Background_pic1 { get; set; }
	/// <summary>
	///背景图2
	/// </summary>
	public int Background_pic2 { get; set; }
	/// <summary>
	///背景图3
	/// </summary>
	public int Background_pic3 { get; set; }
	/// <summary>
	///背景图4
	/// </summary>
	public int Background_pic4 { get; set; }
	/// <summary>
	///背景图5
	/// </summary>
	public int Background_pic5 { get; set; }
	/// <summary>
	///背景图6
	/// </summary>
	public int Background_pic6 { get; set; }
	/// <summary>
	///背景图7
	/// </summary>
	public int Background_pic7 { get; set; }
	/// <summary>
	///背景图8
	/// </summary>
	public int Background_pic8 { get; set; }
	/// <summary>
	///背景图9
	/// </summary>
	public int Background_pic9 { get; set; }
	/// <summary>
	///背景图10
	/// </summary>
	public int Background_pic10 { get; set; }
	/// <summary>
	///背景图11
	/// </summary>
	public int Background_pic11 { get; set; }
	/// <summary>
	///背景图12
	/// </summary>
	public int Background_pic12 { get; set; }
	/// <summary>
	///普通第1箱子所需星数
	/// </summary>
	public int Normal_star_level1 { get; set; }
	/// <summary>
	///普通第2箱子所需星数
	/// </summary>
	public int Normal_star_level2 { get; set; }
	/// <summary>
	///普通第3箱子所需星数
	/// </summary>
	public int Normal_star_level3 { get; set; }
	/// <summary>
	///普通1箱子奖励货币数量
	/// </summary>
	public int Normal_level1_coinnum { get; set; }
	/// <summary>
	///普通2箱子奖励货币数量
	/// </summary>
	public int Normal_level2_coinnum { get; set; }
	/// <summary>
	///普通3箱子奖励货币数量
	/// </summary>
	public int Normal_level3_coinnum { get; set; }
	/// <summary>
	///精英第1箱子所需星数
	/// </summary>
	public int Elite_star_level1 { get; set; }
	/// <summary>
	///精英第2箱子所需星数
	/// </summary>
	public int Elite_star_level2 { get; set; }
	/// <summary>
	///精英第3箱子所需星数
	/// </summary>
	public int Elite_star_level3 { get; set; }
	/// <summary>
	///精英1箱子奖励货币数量
	/// </summary>
	public int Elite_level1_coinnum { get; set; }
	/// <summary>
	///精英2箱子奖励货币数量
	/// </summary>
	public int Elite_level2_coinnum { get; set; }
	/// <summary>
	///精英3箱子奖励货币数量
	/// </summary>
	public int Elite_level3_coinnum { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Campaign module = new DB_Campaign()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Chapter		 = reader.GetString(3),
					Unlocklevel		 = reader.GetInt32(4),
					Comment		 = reader.GetString(5),
					Pre_id		 = reader.GetInt32(6),
					Max_battle		 = reader.GetInt32(7),
					Battleground_id		 = reader.GetInt32(8),
					Prefab_name		 = reader.GetString(9),
					Shining_material		 = reader.GetString(10),
					Background_pic1		 = reader.GetInt32(11),
					Background_pic2		 = reader.GetInt32(12),
					Background_pic3		 = reader.GetInt32(13),
					Background_pic4		 = reader.GetInt32(14),
					Background_pic5		 = reader.GetInt32(15),
					Background_pic6		 = reader.GetInt32(16),
					Background_pic7		 = reader.GetInt32(17),
					Background_pic8		 = reader.GetInt32(18),
					Background_pic9		 = reader.GetInt32(19),
					Background_pic10		 = reader.GetInt32(20),
					Background_pic11		 = reader.GetInt32(21),
					Background_pic12		 = reader.GetInt32(22),
					Normal_star_level1		 = reader.GetInt32(23),
					Normal_star_level2		 = reader.GetInt32(24),
					Normal_star_level3		 = reader.GetInt32(25),
					Normal_level1_coinnum		 = reader.GetInt32(26),
					Normal_level2_coinnum		 = reader.GetInt32(27),
					Normal_level3_coinnum		 = reader.GetInt32(28),
					Elite_star_level1		 = reader.GetInt32(29),
					Elite_star_level2		 = reader.GetInt32(30),
					Elite_star_level3		 = reader.GetInt32(31),
					Elite_level1_coinnum		 = reader.GetInt32(32),
					Elite_level2_coinnum		 = reader.GetInt32(33),
					Elite_level3_coinnum		 = reader.GetInt32(34),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
