using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Commander_tactic : IDB_BaseIntDouble
{
	const string SQL = @"select _index, Id, Tac_Level, Comment, Tac_Name, Tac_center_path, Tac_form_show_path, Tac_description, Tac_detail, Tac_Icon, Tac_selected_Icon, CDTime, Tac_logic0, Tac_effect0, tac_type0, Tac_logic_param0, Tac_logic1, Tac_effect1, tac_type1, Tac_logic_param1, Tac_logic2, Tac_effect2, tac_type2, Tac_logic_param2, Tac_logic3, Tac_effect3, tac_type3, Tac_logic_param3, Tac_logic4, Tac_effect4, tac_type4, Tac_logic_param4, overall_effect from conf_commander_tactic";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///战术ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///战术等级
	/// </summary>
	public int Tac_Level { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///战术名
	/// </summary>
	public string Tac_Name { get; set; }
	/// <summary>
	///战术阵型
	/// </summary>
	public string Tac_center_path { get; set; }
	/// <summary>
	///战术阵型编队展示
	/// </summary>
	public string Tac_form_show_path { get; set; }
	/// <summary>
	///战术描述
	/// </summary>
	public string Tac_description { get; set; }
	/// <summary>
	///战术详述
	/// </summary>
	public string Tac_detail { get; set; }
	/// <summary>
	///战术图标
	/// </summary>
	public int Tac_Icon { get; set; }
	/// <summary>
	///战术选中图标
	/// </summary>
	public int Tac_selected_Icon { get; set; }
	/// <summary>
	///冷却时间
	/// </summary>
	public int CDTime { get; set; }
	/// <summary>
	///战术逻辑1
	/// </summary>
	public int Tac_logic0 { get; set; }
	/// <summary>
	///战术效果1
	/// </summary>
	public int Tac_effect0 { get; set; }
	/// <summary>
	///战术效果类型1
	/// </summary>
	public int Tac_type0 { get; set; }
	/// <summary>
	///逻辑参数1
	/// </summary>
	public float Tac_logic_param0 { get; set; }
	/// <summary>
	///战术逻辑2
	/// </summary>
	public int Tac_logic1 { get; set; }
	/// <summary>
	///战术效果2
	/// </summary>
	public int Tac_effect1 { get; set; }
	/// <summary>
	///战术类型2
	/// </summary>
	public int Tac_type1 { get; set; }
	/// <summary>
	///逻辑参数2
	/// </summary>
	public float Tac_logic_param1 { get; set; }
	/// <summary>
	///战术逻辑3
	/// </summary>
	public int Tac_logic2 { get; set; }
	/// <summary>
	///战术效果3
	/// </summary>
	public int Tac_effect2 { get; set; }
	/// <summary>
	///战术类型3
	/// </summary>
	public int Tac_type2 { get; set; }
	/// <summary>
	///逻辑参数3
	/// </summary>
	public float Tac_logic_param2 { get; set; }
	/// <summary>
	///战术逻辑4
	/// </summary>
	public int Tac_logic3 { get; set; }
	/// <summary>
	///战术效果4
	/// </summary>
	public int Tac_effect3 { get; set; }
	/// <summary>
	///战术类型4
	/// </summary>
	public int Tac_type3 { get; set; }
	/// <summary>
	///逻辑参数4
	/// </summary>
	public float Tac_logic_param3 { get; set; }
	/// <summary>
	///战术逻辑5
	/// </summary>
	public int Tac_logic4 { get; set; }
	/// <summary>
	///战术效果5
	/// </summary>
	public int Tac_effect4 { get; set; }
	/// <summary>
	///战术类型5
	/// </summary>
	public int Tac_type4 { get; set; }
	/// <summary>
	///逻辑参数5
	/// </summary>
	public float Tac_logic_param4 { get; set; }
	/// <summary>
	///全局效果
	/// </summary>
	public int Overall_effect { get; set; }

	static Dictionary<int, Dictionary<int, IDB_BaseIntDouble>> LoadDB()
	{
		Dictionary<int, Dictionary<int, IDB_BaseIntDouble>> tmp = new Dictionary<int, Dictionary<int, IDB_BaseIntDouble>>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Commander_tactic module = new DB_Commander_tactic()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Tac_Level		 = reader.GetInt32(2),
					Comment		 = reader.GetString(3),
					Tac_Name		 = reader.GetString(4),
					Tac_center_path		 = reader.GetString(5),
					Tac_form_show_path		 = reader.GetString(6),
					Tac_description		 = reader.GetString(7),
					Tac_detail		 = reader.GetString(8),
					Tac_Icon		 = reader.GetInt32(9),
					Tac_selected_Icon		 = reader.GetInt32(10),
					CDTime		 = reader.GetInt32(11),
					Tac_logic0		 = reader.GetInt32(12),
					Tac_effect0		 = reader.GetInt32(13),
					Tac_type0		 = reader.GetInt32(14),
					Tac_logic_param0		 = reader.GetFloat(15),
					Tac_logic1		 = reader.GetInt32(16),
					Tac_effect1		 = reader.GetInt32(17),
					Tac_type1		 = reader.GetInt32(18),
					Tac_logic_param1		 = reader.GetFloat(19),
					Tac_logic2		 = reader.GetInt32(20),
					Tac_effect2		 = reader.GetInt32(21),
					Tac_type2		 = reader.GetInt32(22),
					Tac_logic_param2		 = reader.GetFloat(23),
					Tac_logic3		 = reader.GetInt32(24),
					Tac_effect3		 = reader.GetInt32(25),
					Tac_type3		 = reader.GetInt32(26),
					Tac_logic_param3		 = reader.GetFloat(27),
					Tac_logic4		 = reader.GetInt32(28),
					Tac_effect4		 = reader.GetInt32(29),
					Tac_type4		 = reader.GetInt32(30),
					Tac_logic_param4		 = reader.GetFloat(31),
					Overall_effect		 = reader.GetInt32(32),
				};
				if (!tmp.ContainsKey(module.Id))
				{
					var tmpsub = new Dictionary<int, IDB_BaseIntDouble>();
					tmp.Add(module.Id, tmpsub);
				}
				tmp[module.Id].Add(module.Tac_Level, module);
			}
		});
		return tmp;
	}
}
