using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Commander_icon : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, hat_id, face_id, clothes_id, prefab_name from conf_commander_icon";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///帽子id
	/// </summary>
	public int Hat_id { get; set; }
	/// <summary>
	///面部id
	/// </summary>
	public int Face_id { get; set; }
	/// <summary>
	///领子id
	/// </summary>
	public int Clothes_id { get; set; }
	/// <summary>
	///预设名
	/// </summary>
	public string Prefab_name { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Commander_icon module = new DB_Commander_icon()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Hat_id		 = reader.GetInt32(3),
					Face_id		 = reader.GetInt32(4),
					Clothes_id		 = reader.GetInt32(5),
					Prefab_name		 = reader.GetString(6),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
