using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Clue : IDB_BaseInt
{
	const string SQL = @"select _index, id, battle_id, attach_id, pre_dialog, after_dilaog, Icon_id from conf_clue";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///线索ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///战斗ID
	/// </summary>
	public int Battle_id { get; set; }
	/// <summary>
	///归属ID
	/// </summary>
	public int Attach_id { get; set; }
	/// <summary>
	///开始剧情对话
	/// </summary>
	public int Pre_dialog { get; set; }
	/// <summary>
	///结束剧情对话
	/// </summary>
	public int After_dilaog { get; set; }
	/// <summary>
	///IconID
	/// </summary>
	public int Icon_id { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Clue module = new DB_Clue()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Battle_id		 = reader.GetInt32(2),
					Attach_id		 = reader.GetInt32(3),
					Pre_dialog		 = reader.GetInt32(4),
					After_dilaog		 = reader.GetInt32(5),
					Icon_id		 = reader.GetInt32(6),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
