using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Conversation_info : IDB_BaseInt
{
	const string SQL = @"select _index, conversation_id, conversation_next_id, dev_des, conversation_type, bg_picture_res, bg_sound_res, general_portrait_res, general_portrait_res_dir, general_portrait_res_reversal, general_name_text, text_output_delay, conversation_text, last_time, option1_text, option1_reward_id, option1_consume_id, option2_text, option2_reward_id, option2_consume_id from conf_conversation_info";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///对话ID
	/// </summary>
	public int Conversation_id { get; set; }
	/// <summary>
	///下一个对话ID
	/// </summary>
	public int Conversation_next_id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Dev_des { get; set; }
	/// <summary>
	///对话类型1、连续对话2、单段对话
	/// </summary>
	public int Conversation_type { get; set; }
	/// <summary>
	///调用插图资源完整路径资源路径：改变或切换场景插图0、保留原有场景插图-1、关闭所有场景插图
	/// </summary>
	public string Bg_picture_res { get; set; }
	/// <summary>
	///调用音效资源索引ID
	/// </summary>
	public int Bg_sound_res { get; set; }
	/// <summary>
	///对话卡牌资源
	/// </summary>
	public int General_portrait_res { get; set; }
	/// <summary>
	///卡牌位置
	/// </summary>
	public int General_portrait_res_dir { get; set; }
	/// <summary>
	///卡牌是否翻转0-不翻转1-翻转
	/// </summary>
	public int General_portrait_res_reversal { get; set; }
	/// <summary>
	///武将名称字典ID
	/// </summary>
	public string General_name_text { get; set; }
	/// <summary>
	///对话文本出现延迟(毫秒)
	/// </summary>
	public int Text_output_delay { get; set; }
	/// <summary>
	///对话文本字典ID（单行字数32，标点占1）
	/// </summary>
	public string Conversation_text { get; set; }
	/// <summary>
	///平均持续时间
	/// </summary>
	public int Last_time { get; set; }
	/// <summary>
	///对话选项1文本字典ID
	/// </summary>
	public string Option1_text { get; set; }
	/// <summary>
	///选项1调用奖励组
	/// </summary>
	public int Option1_reward_id { get; set; }
	/// <summary>
	///选项1调用消耗组
	/// </summary>
	public int Option1_consume_id { get; set; }
	/// <summary>
	///对话选项2文本字典ID
	/// </summary>
	public string Option2_text { get; set; }
	/// <summary>
	///选项2调用奖励组
	/// </summary>
	public int Option2_reward_id { get; set; }
	/// <summary>
	///选项2调用消耗组
	/// </summary>
	public int Option2_consume_id { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Conversation_info module = new DB_Conversation_info()
				{
					_index		 = reader.GetInt32(0),
					Conversation_id		 = reader.GetInt32(1),
					Conversation_next_id		 = reader.GetInt32(2),
					Dev_des		 = reader.GetString(3),
					Conversation_type		 = reader.GetInt32(4),
					Bg_picture_res		 = reader.GetString(5),
					Bg_sound_res		 = reader.GetInt32(6),
					General_portrait_res		 = reader.GetInt32(7),
					General_portrait_res_dir		 = reader.GetInt32(8),
					General_portrait_res_reversal		 = reader.GetInt32(9),
					General_name_text		 = reader.GetString(10),
					Text_output_delay		 = reader.GetInt32(11),
					Conversation_text		 = reader.GetString(12),
					Last_time		 = reader.GetInt32(13),
					Option1_text		 = reader.GetString(14),
					Option1_reward_id		 = reader.GetInt32(15),
					Option1_consume_id		 = reader.GetInt32(16),
					Option2_text		 = reader.GetString(17),
					Option2_reward_id		 = reader.GetInt32(18),
					Option2_consume_id		 = reader.GetInt32(19),
				};
				tmp.Add(module.Conversation_id, module);
			}
		});
		return tmp;
	}
}
