using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Commander_attr : IDB_BaseInt
{
	const string SQL = @"select _index, Id, Comment, Commander_Name, description, Evolve_Id, Evolve_Rule, Rare, Evolved_Id, Level, Level_Limit, Base_Exp, Combo0, Combo1, Icon, Icon_inbattle, Tac0, Tac1, Tac2, Skill0, Skilllevel0, Skill1, Skilllevel1, Skill2, Skilllevel2 from conf_commander_attr";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///指挥官id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///指挥官名字
	/// </summary>
	public string Commander_Name { get; set; }
	/// <summary>
	///描述文本
	/// </summary>
	public string Description { get; set; }
	/// <summary>
	///识别id
	/// </summary>
	public int Evolve_Id { get; set; }
	/// <summary>
	///品质提升条件
	/// </summary>
	public int Evolve_Rule { get; set; }
	/// <summary>
	///品质
	/// </summary>
	public int Rare { get; set; }
	/// <summary>
	///提升后id
	/// </summary>
	public int Evolved_Id { get; set; }
	/// <summary>
	///初始等级
	/// </summary>
	public int Level { get; set; }
	/// <summary>
	///军阶上限
	/// </summary>
	public int Level_Limit { get; set; }
	/// <summary>
	///初始化等级经验
	/// </summary>
	public int Base_Exp { get; set; }
	/// <summary>
	///组合1
	/// </summary>
	public int Combo0 { get; set; }
	/// <summary>
	///组合2
	/// </summary>
	public int Combo1 { get; set; }
	/// <summary>
	///头像图标
	/// </summary>
	public int Icon { get; set; }
	/// <summary>
	///头像图标2
	/// </summary>
	public int Icon_inbattle { get; set; }
	/// <summary>
	///战术1
	/// </summary>
	public int Tac0 { get; set; }
	/// <summary>
	///战术2
	/// </summary>
	public int Tac1 { get; set; }
	/// <summary>
	///战术3
	/// </summary>
	public int Tac2 { get; set; }
	/// <summary>
	///技能1
	/// </summary>
	public int Skill0 { get; set; }
	/// <summary>
	///技能1等级
	/// </summary>
	public int Skilllevel0 { get; set; }
	/// <summary>
	///技能2
	/// </summary>
	public int Skill1 { get; set; }
	/// <summary>
	///技能2等级
	/// </summary>
	public int Skilllevel1 { get; set; }
	/// <summary>
	///技能3
	/// </summary>
	public int Skill2 { get; set; }
	/// <summary>
	///技能3等级
	/// </summary>
	public int Skilllevel2 { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Commander_attr module = new DB_Commander_attr()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Commander_Name		 = reader.GetString(3),
					Description		 = reader.GetString(4),
					Evolve_Id		 = reader.GetInt32(5),
					Evolve_Rule		 = reader.GetInt32(6),
					Rare		 = reader.GetInt32(7),
					Evolved_Id		 = reader.GetInt32(8),
					Level		 = reader.GetInt32(9),
					Level_Limit		 = reader.GetInt32(10),
					Base_Exp		 = reader.GetInt32(11),
					Combo0		 = reader.GetInt32(12),
					Combo1		 = reader.GetInt32(13),
					Icon		 = reader.GetInt32(14),
					Icon_inbattle		 = reader.GetInt32(15),
					Tac0		 = reader.GetInt32(16),
					Tac1		 = reader.GetInt32(17),
					Tac2		 = reader.GetInt32(18),
					Skill0		 = reader.GetInt32(19),
					Skilllevel0		 = reader.GetInt32(20),
					Skill1		 = reader.GetInt32(21),
					Skilllevel1		 = reader.GetInt32(22),
					Skill2		 = reader.GetInt32(23),
					Skilllevel2		 = reader.GetInt32(24),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
