using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Equip_level_rule : IDB_BaseInt
{
	const string SQL = @"select _index, level, next_level, slot2cost, slot3cost, slot4cost, slot5cost, slot6cost from conf_equip_level_rule";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///装备等级
	/// </summary>
	public int Level { get; set; }
	/// <summary>
	///装备下一等级
	/// </summary>
	public int Next_level { get; set; }
	/// <summary>
	///火炮升级花费
	/// </summary>
	public int Slot2cost { get; set; }
	/// <summary>
	///炮塔升级花费
	/// </summary>
	public int Slot3cost { get; set; }
	/// <summary>
	///引擎升级花费
	/// </summary>
	public int Slot4cost { get; set; }
	/// <summary>
	///底盘升级花费
	/// </summary>
	public int Slot5cost { get; set; }
	/// <summary>
	///火控升级花费
	/// </summary>
	public int Slot6cost { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Equip_level_rule module = new DB_Equip_level_rule()
				{
					_index		 = reader.GetInt32(0),
					Level		 = reader.GetInt32(1),
					Next_level		 = reader.GetInt32(2),
					Slot2cost		 = reader.GetInt32(3),
					Slot3cost		 = reader.GetInt32(4),
					Slot4cost		 = reader.GetInt32(5),
					Slot5cost		 = reader.GetInt32(6),
					Slot6cost		 = reader.GetInt32(7),
				};
				tmp.Add(module.Level, module);
			}
		});
		return tmp;
	}
}
