using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Equip_star_rule : IDB_BaseInt
{
	const string SQL = @"select _index, star_level, quality_name, luck_change_type, luck_change_value, rate_region, return_material1_id, amount_material1, return_material2_id, amount_material2, return_material3_id, amount_material3, retain_money from conf_equip_star_rule";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///星星等级
	/// </summary>
	public int Star_level { get; set; }
	/// <summary>
	///品质名字
	/// </summary>
	public string Quality_name { get; set; }
	/// <summary>
	///幸运变化类型
	/// </summary>
	public int Luck_change_type { get; set; }
	/// <summary>
	///幸运变化数值
	/// </summary>
	public int Luck_change_value { get; set; }
	/// <summary>
	///概率区间
	/// </summary>
	public int Rate_region { get; set; }
	/// <summary>
	///退回材料1
	/// </summary>
	public int Return_material1_id { get; set; }
	/// <summary>
	///退回材料数量1
	/// </summary>
	public int Amount_material1 { get; set; }
	/// <summary>
	///退回材料2
	/// </summary>
	public int Return_material2_id { get; set; }
	/// <summary>
	///退回材料数量2
	/// </summary>
	public int Amount_material2 { get; set; }
	/// <summary>
	///退回材料3
	/// </summary>
	public int Return_material3_id { get; set; }
	/// <summary>
	///退回材料数量3
	/// </summary>
	public int Amount_material3 { get; set; }
	/// <summary>
	///保留属性所需金币
	/// </summary>
	public int Retain_money { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Equip_star_rule module = new DB_Equip_star_rule()
				{
					_index		 = reader.GetInt32(0),
					Star_level		 = reader.GetInt32(1),
					Quality_name		 = reader.GetString(2),
					Luck_change_type		 = reader.GetInt32(3),
					Luck_change_value		 = reader.GetInt32(4),
					Rate_region		 = reader.GetInt32(5),
					Return_material1_id		 = reader.GetInt32(6),
					Amount_material1		 = reader.GetInt32(7),
					Return_material2_id		 = reader.GetInt32(8),
					Amount_material2		 = reader.GetInt32(9),
					Return_material3_id		 = reader.GetInt32(10),
					Amount_material3		 = reader.GetInt32(11),
					Retain_money		 = reader.GetInt32(12),
				};
				tmp.Add(module.Star_level, module);
			}
		});
		return tmp;
	}
}
