using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Equip_star_attr : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, Fe_floor, Fe_upper, Cu_floor, Cu_upper, AG_floor, AG_upper, AU_floor, AU_upper, DO_floor, DO_upper from conf_equip_star_attr";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///属性ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///属性名
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///铁下限
	/// </summary>
	public float Fe_floor { get; set; }
	/// <summary>
	///上限
	/// </summary>
	public float Fe_upper { get; set; }
	/// <summary>
	///铜下限
	/// </summary>
	public float Cu_floor { get; set; }
	/// <summary>
	///上限
	/// </summary>
	public float Cu_upper { get; set; }
	/// <summary>
	///银下限
	/// </summary>
	public float AG_floor { get; set; }
	/// <summary>
	///上限
	/// </summary>
	public float AG_upper { get; set; }
	/// <summary>
	///金下限
	/// </summary>
	public float AU_floor { get; set; }
	/// <summary>
	///上限
	/// </summary>
	public float AU_upper { get; set; }
	/// <summary>
	///钻下限
	/// </summary>
	public float DO_floor { get; set; }
	/// <summary>
	///上限
	/// </summary>
	public float DO_upper { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Equip_star_attr module = new DB_Equip_star_attr()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Fe_floor		 = reader.GetFloat(3),
					Fe_upper		 = reader.GetFloat(4),
					Cu_floor		 = reader.GetFloat(5),
					Cu_upper		 = reader.GetFloat(6),
					AG_floor		 = reader.GetFloat(7),
					AG_upper		 = reader.GetFloat(8),
					AU_floor		 = reader.GetFloat(9),
					AU_upper		 = reader.GetFloat(10),
					DO_floor		 = reader.GetFloat(11),
					DO_upper		 = reader.GetFloat(12),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
