using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Effects_group : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, explode, remains, sound, death_shock, intro_title, intro_text, boss_name, boss_name_text, boss_feature_title, boss_feature_text, boss_shield_icon, show_model_res, boss_texture from conf_effects_group";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///爆炸组
	/// </summary>
	public string Explode { get; set; }
	/// <summary>
	///残骸组
	/// </summary>
	public string Remains { get; set; }
	/// <summary>
	///出场音效
	/// </summary>
	public int Sound { get; set; }
	/// <summary>
	///死亡震屏效果
	/// </summary>
	public int Death_shock { get; set; }
	/// <summary>
	///简介标题文字
	/// </summary>
	public string Intro_title { get; set; }
	/// <summary>
	///简介文本
	/// </summary>
	public string Intro_text { get; set; }
	/// <summary>
	///BOSS战车名字
	/// </summary>
	public string Boss_name { get; set; }
	/// <summary>
	///boss战车描述
	/// </summary>
	public string Boss_name_text { get; set; }
	/// <summary>
	///BOSS特点标题
	/// </summary>
	public string Boss_feature_title { get; set; }
	/// <summary>
	///BOSS特点文本
	/// </summary>
	public string Boss_feature_text { get; set; }
	/// <summary>
	///BOSS盾牌图案
	/// </summary>
	public int Boss_shield_icon { get; set; }
	/// <summary>
	///模型展示
	/// </summary>
	public string Show_model_res { get; set; }
	/// <summary>
	///boss展示图片
	/// </summary>
	public int Boss_texture { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Effects_group module = new DB_Effects_group()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Explode		 = reader.GetString(3),
					Remains		 = reader.GetString(4),
					Sound		 = reader.GetInt32(5),
					Death_shock		 = reader.GetInt32(6),
					Intro_title		 = reader.GetString(7),
					Intro_text		 = reader.GetString(8),
					Boss_name		 = reader.GetString(9),
					Boss_name_text		 = reader.GetString(10),
					Boss_feature_title		 = reader.GetString(11),
					Boss_feature_text		 = reader.GetString(12),
					Boss_shield_icon		 = reader.GetInt32(13),
					Show_model_res		 = reader.GetString(14),
					Boss_texture		 = reader.GetInt32(15),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
