using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Equip_refine_star : IDB_BaseInt
{
	const string SQL = @"select _index, star_level, quality_name, ui_sprite_id from conf_equip_refine_star";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///星星等级
	/// </summary>
	public int Star_level { get; set; }
	/// <summary>
	///品质名字
	/// </summary>
	public string Quality_name { get; set; }
	/// <summary>
	///图标
	/// </summary>
	public int Ui_sprite_id { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Equip_refine_star module = new DB_Equip_refine_star()
				{
					_index		 = reader.GetInt32(0),
					Star_level		 = reader.GetInt32(1),
					Quality_name		 = reader.GetString(2),
					Ui_sprite_id		 = reader.GetInt32(3),
				};
				tmp.Add(module.Star_level, module);
			}
		});
		return tmp;
	}
}
