using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Equip_part_resolve_rule : IDB_BaseInt
{
	const string SQL = @"select _index, id, money_cost, material1_id, material1_cost, material2_id, material2_cost, material3_id, material3_cost, material4_id, material4_cost, level_cost_saving, strength_cost_saving from conf_equip_part_resolve_rule";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///分解规则ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///基础分解游戏币数量
	/// </summary>
	public int Money_cost { get; set; }
	/// <summary>
	///基础分解材料1类型
	/// </summary>
	public int Material1_id { get; set; }
	/// <summary>
	///基础分解材料1数量
	/// </summary>
	public int Material1_cost { get; set; }
	/// <summary>
	///基础分解材料2类型
	/// </summary>
	public int Material2_id { get; set; }
	/// <summary>
	///基础分解材料2数量
	/// </summary>
	public int Material2_cost { get; set; }
	/// <summary>
	///基础分解材料3类型
	/// </summary>
	public int Material3_id { get; set; }
	/// <summary>
	///基础分解材料3数量
	/// </summary>
	public int Material3_cost { get; set; }
	/// <summary>
	///基础分解材料4类型
	/// </summary>
	public int Material4_id { get; set; }
	/// <summary>
	///基础分解材料4数量
	/// </summary>
	public int Material4_cost { get; set; }
	/// <summary>
	///等级消耗保留系数
	/// </summary>
	public float Level_cost_saving { get; set; }
	/// <summary>
	///强化消耗保留系数
	/// </summary>
	public float Strength_cost_saving { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Equip_part_resolve_rule module = new DB_Equip_part_resolve_rule()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Money_cost		 = reader.GetInt32(2),
					Material1_id		 = reader.GetInt32(3),
					Material1_cost		 = reader.GetInt32(4),
					Material2_id		 = reader.GetInt32(5),
					Material2_cost		 = reader.GetInt32(6),
					Material3_id		 = reader.GetInt32(7),
					Material3_cost		 = reader.GetInt32(8),
					Material4_id		 = reader.GetInt32(9),
					Material4_cost		 = reader.GetInt32(10),
					Level_cost_saving		 = reader.GetFloat(11),
					Strength_cost_saving		 = reader.GetFloat(12),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
