using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Equip_attr : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, comment, description, slot, equip_level, rare, origin, suit, refinr_limit, res_equip_id, bind, binding, rebind, bear, weight, selling_price, attr1_type, attr1_value, attr1_growth, attr2_type, attr2_value, attr2_growth, attr3_type, attr3_value, attr3_growth, attr4_type, attr4_value, attr4_growth, attr5_type, attr5_value, attr5_growth, skill, skill_level, type_limit, rareup_level, rareup_rule, rareup_id, levelup_rule, resolve_rule from conf_equip_attr";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///装备ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///装备名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///装备备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///装备描述
	/// </summary>
	public string Description { get; set; }
	/// <summary>
	///部位
	/// </summary>
	public int Slot { get; set; }
	/// <summary>
	///装备级别
	/// </summary>
	public int Equip_level { get; set; }
	/// <summary>
	///品质类型
	/// </summary>
	public int Rare { get; set; }
	/// <summary>
	///装备来源
	/// </summary>
	public int Origin { get; set; }
	/// <summary>
	///装备适用
	/// </summary>
	public int Suit { get; set; }
	/// <summary>
	///精炼上限
	/// </summary>
	public int Refinr_limit { get; set; }
	/// <summary>
	///外形资源
	/// </summary>
	public int Res_equip_id { get; set; }
	/// <summary>
	///绑定类型
	/// </summary>
	public int Bind { get; set; }
	/// <summary>
	///绑定状态
	/// </summary>
	public int Binding { get; set; }
	/// <summary>
	///解绑成本
	/// </summary>
	public int Rebind { get; set; }
	/// <summary>
	///承载
	/// </summary>
	public int Bear { get; set; }
	/// <summary>
	///自重
	/// </summary>
	public int Weight { get; set; }
	/// <summary>
	///出售价值
	/// </summary>
	public int Selling_price { get; set; }
	/// <summary>
	///基本属性类型1
	/// </summary>
	public int Attr1_type { get; set; }
	/// <summary>
	///属性1值
	/// </summary>
	public float Attr1_value { get; set; }
	/// <summary>
	///属性1成长值
	/// </summary>
	public float Attr1_growth { get; set; }
	/// <summary>
	///基本属性类型2
	/// </summary>
	public int Attr2_type { get; set; }
	/// <summary>
	///属性2值
	/// </summary>
	public float Attr2_value { get; set; }
	/// <summary>
	///属性2成长值
	/// </summary>
	public float Attr2_growth { get; set; }
	/// <summary>
	///基本属性类型3
	/// </summary>
	public int Attr3_type { get; set; }
	/// <summary>
	///属性3值
	/// </summary>
	public float Attr3_value { get; set; }
	/// <summary>
	///属性3成长值
	/// </summary>
	public float Attr3_growth { get; set; }
	/// <summary>
	///基本属性类型4
	/// </summary>
	public int Attr4_type { get; set; }
	/// <summary>
	///属性4值
	/// </summary>
	public float Attr4_value { get; set; }
	/// <summary>
	///属性4成长值
	/// </summary>
	public float Attr4_growth { get; set; }
	/// <summary>
	///基本属性类型5
	/// </summary>
	public int Attr5_type { get; set; }
	/// <summary>
	///属性5值
	/// </summary>
	public float Attr5_value { get; set; }
	/// <summary>
	///属性5成长值
	/// </summary>
	public float Attr5_growth { get; set; }
	/// <summary>
	///火炮技能
	/// </summary>
	public int Skill { get; set; }
	/// <summary>
	///火炮技能等级
	/// </summary>
	public int Skill_level { get; set; }
	/// <summary>
	///装备车型限制
	/// </summary>
	public int Type_limit { get; set; }
	/// <summary>
	///品质提升等级
	/// </summary>
	public int Rareup_level { get; set; }
	/// <summary>
	///品质提升条件
	/// </summary>
	public int Rareup_rule { get; set; }
	/// <summary>
	///品质提升后id
	/// </summary>
	public int Rareup_id { get; set; }
	/// <summary>
	///升级条件
	/// </summary>
	public int Levelup_rule { get; set; }
	/// <summary>
	///拆解规则
	/// </summary>
	public int Resolve_rule { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Equip_attr module = new DB_Equip_attr()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Comment		 = reader.GetString(3),
					Description		 = reader.GetString(4),
					Slot		 = reader.GetInt32(5),
					Equip_level		 = reader.GetInt32(6),
					Rare		 = reader.GetInt32(7),
					Origin		 = reader.GetInt32(8),
					Suit		 = reader.GetInt32(9),
					Refinr_limit		 = reader.GetInt32(10),
					Res_equip_id		 = reader.GetInt32(11),
					Bind		 = reader.GetInt32(12),
					Binding		 = reader.GetInt32(13),
					Rebind		 = reader.GetInt32(14),
					Bear		 = reader.GetInt32(15),
					Weight		 = reader.GetInt32(16),
					Selling_price		 = reader.GetInt32(17),
					Attr1_type		 = reader.GetInt32(18),
					Attr1_value		 = reader.GetFloat(19),
					Attr1_growth		 = reader.GetFloat(20),
					Attr2_type		 = reader.GetInt32(21),
					Attr2_value		 = reader.GetFloat(22),
					Attr2_growth		 = reader.GetFloat(23),
					Attr3_type		 = reader.GetInt32(24),
					Attr3_value		 = reader.GetFloat(25),
					Attr3_growth		 = reader.GetFloat(26),
					Attr4_type		 = reader.GetInt32(27),
					Attr4_value		 = reader.GetFloat(28),
					Attr4_growth		 = reader.GetFloat(29),
					Attr5_type		 = reader.GetInt32(30),
					Attr5_value		 = reader.GetFloat(31),
					Attr5_growth		 = reader.GetFloat(32),
					Skill		 = reader.GetInt32(33),
					Skill_level		 = reader.GetInt32(34),
					Type_limit		 = reader.GetInt32(35),
					Rareup_level		 = reader.GetInt32(36),
					Rareup_rule		 = reader.GetInt32(37),
					Rareup_id		 = reader.GetInt32(38),
					Levelup_rule		 = reader.GetInt32(39),
					Resolve_rule		 = reader.GetInt32(40),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
