using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Equip_type_limit : IDB_BaseInt
{
	const string SQL = @"select _index, type_limit, type_name from conf_equip_type_limit";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///装备类型限制
	/// </summary>
	public int Type_limit { get; set; }
	/// <summary>
	///类型
	/// </summary>
	public string Type_name { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Equip_type_limit module = new DB_Equip_type_limit()
				{
					_index		 = reader.GetInt32(0),
					Type_limit		 = reader.GetInt32(1),
					Type_name		 = reader.GetString(2),
				};
				tmp.Add(module.Type_limit, module);
			}
		});
		return tmp;
	}
}
