using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Glory_event : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, event_type, rolelevel_min, rolelevel_max, battle_event_id, reward, cd_increased, cd_limit, reward_text, back_star, icon_star, back_open, icon_open, back_end, icon_end, mesh_name from conf_glory_event";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///关卡id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///关卡类型
	/// </summary>
	public int Event_type { get; set; }
	/// <summary>
	///筛选等级下限
	/// </summary>
	public int Rolelevel_min { get; set; }
	/// <summary>
	///筛选等级上限
	/// </summary>
	public int Rolelevel_max { get; set; }
	/// <summary>
	///战场id
	/// </summary>
	public int Battle_event_id { get; set; }
	/// <summary>
	///事件奖励
	/// </summary>
	public int Reward { get; set; }
	/// <summary>
	///战斗增加cd
	/// </summary>
	public int Cd_increased { get; set; }
	/// <summary>
	///CD上限
	/// </summary>
	public int Cd_limit { get; set; }
	/// <summary>
	///领奖文本
	/// </summary>
	public string Reward_text { get; set; }
	/// <summary>
	///初始底板
	/// </summary>
	public int Back_star { get; set; }
	/// <summary>
	///初始图标
	/// </summary>
	public int Icon_star { get; set; }
	/// <summary>
	///翻卡底板
	/// </summary>
	public int Back_open { get; set; }
	/// <summary>
	///翻卡图标
	/// </summary>
	public int Icon_open { get; set; }
	/// <summary>
	///击杀底板
	/// </summary>
	public int Back_end { get; set; }
	/// <summary>
	///击杀图标
	/// </summary>
	public int Icon_end { get; set; }
	/// <summary>
	///特效路径
	/// </summary>
	public string Mesh_name { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Glory_event module = new DB_Glory_event()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Event_type		 = reader.GetInt32(3),
					Rolelevel_min		 = reader.GetInt32(4),
					Rolelevel_max		 = reader.GetInt32(5),
					Battle_event_id		 = reader.GetInt32(6),
					Reward		 = reader.GetInt32(7),
					Cd_increased		 = reader.GetInt32(8),
					Cd_limit		 = reader.GetInt32(9),
					Reward_text		 = reader.GetString(10),
					Back_star		 = reader.GetInt32(11),
					Icon_star		 = reader.GetInt32(12),
					Back_open		 = reader.GetInt32(13),
					Icon_open		 = reader.GetInt32(14),
					Back_end		 = reader.GetInt32(15),
					Icon_end		 = reader.GetInt32(16),
					Mesh_name		 = reader.GetString(17),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
