using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Glory_event_battle_ui_pos : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, pos from conf_glory_event_battle_ui_pos";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///位置id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///坐标
	/// </summary>
	public string Pos { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Glory_event_battle_ui_pos module = new DB_Glory_event_battle_ui_pos()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Pos		 = reader.GetString(3),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
