using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Limit : IDB_BaseInt
{
	const string SQL = @"select _index, role_level from conf_limit";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///玩家等级上限
	/// </summary>
	public int Role_level { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Limit module = new DB_Limit()
				{
					_index		 = reader.GetInt32(0),
					Role_level		 = reader.GetInt32(1),
				};
				tmp.Add(module.Role_level, module);
			}
		});
		return tmp;
	}
}
