using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Loading : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, type, res, title, description, texture_path, texture from conf_loading";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///id，包含指挥官和坦克两种
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///美术资源索引，1=指挥官，res列从conf_commander_icon_client中读取；2=坦克，res数据从conf_res_tank_client中读取
	/// </summary>
	public int Type { get; set; }
	/// <summary>
	///美术资源id
	/// </summary>
	public string Res { get; set; }
	/// <summary>
	///描述文字标题字典号
	/// </summary>
	public string Title { get; set; }
	/// <summary>
	///文字描述字典号
	/// </summary>
	public string Description { get; set; }
	/// <summary>
	///涂装贴图路径
	/// </summary>
	public string Texture_path { get; set; }
	/// <summary>
	///涂装贴图文件
	/// </summary>
	public string Texture { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Loading module = new DB_Loading()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Type		 = reader.GetInt32(3),
					Res		 = reader.GetString(4),
					Title		 = reader.GetString(5),
					Description		 = reader.GetString(6),
					Texture_path		 = reader.GetString(7),
					Texture		 = reader.GetString(8),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
