using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Material : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, description, comment, ui_sprite_id from conf_material";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///材料ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///材料名字
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///材料描述
	/// </summary>
	public string Description { get; set; }
	/// <summary>
	///材料备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///图标ID
	/// </summary>
	public int Ui_sprite_id { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Material module = new DB_Material()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Description		 = reader.GetString(3),
					Comment		 = reader.GetString(4),
					Ui_sprite_id		 = reader.GetInt32(5),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
