using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Newbie_flow : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, comment, condition, isHasGoHome from conf_newbie_flow";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///流程id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///流程名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///条件
	/// </summary>
	public string Condition { get; set; }
	/// <summary>
	///是否需要返回主界面
	/// </summary>
	public int IsHasGoHome { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Newbie_flow module = new DB_Newbie_flow()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Comment		 = reader.GetString(3),
					Condition		 = reader.GetString(4),
					IsHasGoHome		 = reader.GetInt32(5),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
