using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Newbie_condition : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, param1, param2, type from conf_newbie_condition";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///判定条件
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///参数1
	/// </summary>
	public int Param1 { get; set; }
	/// <summary>
	///参数2
	/// </summary>
	public float Param2 { get; set; }
	/// <summary>
	///触发条件
	/// </summary>
	public int Type { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Newbie_condition module = new DB_Newbie_condition()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Param1		 = reader.GetInt32(3),
					Param2		 = reader.GetFloat(4),
					Type		 = reader.GetInt32(5),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
