using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Newbie_flow_task : IDB_BaseInt
{
	const string SQL = @"select _index, task_id, comment, flow_id, order_id from conf_newbie_flow_task";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///任务id
	/// </summary>
	public int Task_id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///流程id
	/// </summary>
	public int Flow_id { get; set; }
	/// <summary>
	///子步骤
	/// </summary>
	public int Order_id { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Newbie_flow_task module = new DB_Newbie_flow_task()
				{
					_index		 = reader.GetInt32(0),
					Task_id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Flow_id		 = reader.GetInt32(3),
					Order_id		 = reader.GetInt32(4),
				};
				tmp.Add(module.Task_id, module);
			}
		});
		return tmp;
	}
}
