using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Purchase_goods : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, waretype, count, currency, price, description1, description2, description3, recharge, exrecharge, firstexrecharge, secondexrecharge, thirdexrecharge, recommend, icon, count_icon, moondays, moondailyrecharge from conf_purchase_goods";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///物品id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///物品类型
	/// </summary>
	public int Waretype { get; set; }
	/// <summary>
	///钻石数量
	/// </summary>
	public int Count { get; set; }
	/// <summary>
	///货币类型
	/// </summary>
	public string Currency { get; set; }
	/// <summary>
	///物品价格
	/// </summary>
	public float Price { get; set; }
	/// <summary>
	///描述1
	/// </summary>
	public string Description1 { get; set; }
	/// <summary>
	///描述2
	/// </summary>
	public string Description2 { get; set; }
	/// <summary>
	///描述3
	/// </summary>
	public string Description3 { get; set; }
	/// <summary>
	///充值获得量
	/// </summary>
	public int Recharge { get; set; }
	/// <summary>
	///非首充获得量
	/// </summary>
	public int Exrecharge { get; set; }
	/// <summary>
	///首充额外获得
	/// </summary>
	public int Firstexrecharge { get; set; }
	/// <summary>
	///二次额外获得
	/// </summary>
	public int Secondexrecharge { get; set; }
	/// <summary>
	///三次额外获得
	/// </summary>
	public int Thirdexrecharge { get; set; }
	/// <summary>
	///是否推荐
	/// </summary>
	public int Recommend { get; set; }
	/// <summary>
	///物品图标
	/// </summary>
	public int Icon { get; set; }
	/// <summary>
	///金额图标
	/// </summary>
	public int Count_icon { get; set; }
	/// <summary>
	///月卡天数
	/// </summary>
	public int Moondays { get; set; }
	/// <summary>
	///月卡每天返还
	/// </summary>
	public int Moondailyrecharge { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Purchase_goods module = new DB_Purchase_goods()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Waretype		 = reader.GetInt32(3),
					Count		 = reader.GetInt32(4),
					Currency		 = reader.GetString(5),
					Price		 = reader.GetFloat(6),
					Description1		 = reader.GetString(7),
					Description2		 = reader.GetString(8),
					Description3		 = reader.GetString(9),
					Recharge		 = reader.GetInt32(10),
					Exrecharge		 = reader.GetInt32(11),
					Firstexrecharge		 = reader.GetInt32(12),
					Secondexrecharge		 = reader.GetInt32(13),
					Thirdexrecharge		 = reader.GetInt32(14),
					Recommend		 = reader.GetInt32(15),
					Icon		 = reader.GetInt32(16),
					Count_icon		 = reader.GetInt32(17),
					Moondays		 = reader.GetInt32(18),
					Moondailyrecharge		 = reader.GetInt32(19),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
