using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Player : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, icon_id, portrait_id, gender from conf_player";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///头像id
	/// </summary>
	public int Icon_id { get; set; }
	/// <summary>
	///半身像id
	/// </summary>
	public int Portrait_id { get; set; }
	/// <summary>
	///性别1=男，0=女
	/// </summary>
	public int Gender { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Player module = new DB_Player()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Icon_id		 = reader.GetInt32(3),
					Portrait_id		 = reader.GetInt32(4),
					Gender		 = reader.GetInt32(5),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
