using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Prop_compose : IDB_BaseInt
{
	const string SQL = @"select _index, compose_id, comment, currency, price, prop1, propnum1, prop2, propnum2, prop3, propnum3 from conf_prop_compose";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///配方id
	/// </summary>
	public int Compose_id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///消耗货币类型
	/// </summary>
	public int Currency { get; set; }
	/// <summary>
	///消耗货币数量
	/// </summary>
	public int Price { get; set; }
	/// <summary>
	///合成材料1
	/// </summary>
	public int Prop1 { get; set; }
	/// <summary>
	///材料1数量
	/// </summary>
	public int Propnum1 { get; set; }
	/// <summary>
	///合成材料2
	/// </summary>
	public int Prop2 { get; set; }
	/// <summary>
	///材料2数量
	/// </summary>
	public int Propnum2 { get; set; }
	/// <summary>
	///合成材料3
	/// </summary>
	public int Prop3 { get; set; }
	/// <summary>
	///材料3数量
	/// </summary>
	public int Propnum3 { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Prop_compose module = new DB_Prop_compose()
				{
					_index		 = reader.GetInt32(0),
					Compose_id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Currency		 = reader.GetInt32(3),
					Price		 = reader.GetInt32(4),
					Prop1		 = reader.GetInt32(5),
					Propnum1		 = reader.GetInt32(6),
					Prop2		 = reader.GetInt32(7),
					Propnum2		 = reader.GetInt32(8),
					Prop3		 = reader.GetInt32(9),
					Propnum3		 = reader.GetInt32(10),
				};
				tmp.Add(module.Compose_id, module);
			}
		});
		return tmp;
	}
}
