using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Res_series : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, ui_sprite_id, att_choose_text from conf_res_series";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///表现类型ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///表现类型名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///图标ID
	/// </summary>
	public int Ui_sprite_id { get; set; }
	/// <summary>
	///坦克攻击倾向描述
	/// </summary>
	public string Att_choose_text { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Res_series module = new DB_Res_series()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Ui_sprite_id		 = reader.GetInt32(3),
					Att_choose_text		 = reader.GetString(4),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
