using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Res_loading : IDB_BaseString
{
	const string SQL = @"select _index, key, value, background_img_path, background_img_name from conf_res_loading";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///键值
	/// </summary>
	public string Key { get; set; }
	/// <summary>
	///场景序号
	/// </summary>
	public int Value { get; set; }
	/// <summary>
	///背景图路径
	/// </summary>
	public string Background_img_path { get; set; }
	/// <summary>
	///背景图名称
	/// </summary>
	public string Background_img_name { get; set; }

	static Dictionary<string, IDB_BaseString> LoadDB()
	{
		Dictionary<string, IDB_BaseString> tmp = new Dictionary<string, IDB_BaseString>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Res_loading module = new DB_Res_loading()
				{
					_index		 = reader.GetInt32(0),
					Key		 = reader.GetString(1),
					Value		 = reader.GetInt32(2),
					Background_img_path		 = reader.GetString(3),
					Background_img_name		 = reader.GetString(4),
				};
				tmp.Add(module.Key, module);
			}
		});
		return tmp;
	}
}
