using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Res_country : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, ui_sprite_id from conf_res_country";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///国籍ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///国籍图标ID
	/// </summary>
	public int Ui_sprite_id { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Res_country module = new DB_Res_country()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Ui_sprite_id		 = reader.GetInt32(3),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
