using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Res_quality : IDB_BaseInt
{
	const string SQL = @"select _index, id, ui_sprite_id, star_level_text from conf_res_quality";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///星级ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///星级图标ID
	/// </summary>
	public int Ui_sprite_id { get; set; }
	/// <summary>
	///星星等级文本
	/// </summary>
	public string Star_level_text { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Res_quality module = new DB_Res_quality()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Ui_sprite_id		 = reader.GetInt32(2),
					Star_level_text		 = reader.GetString(3),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
