using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Reward : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, money, strategy_coin, militaryexploit, coin, common_exp, leader_exp, commander_exp, tank_exp, material1, materialnum1, material2, materialnum2, material3, materialnum3, material4, materialnum4, prop1, propnum1, prop2, propnum2, prop3, propnum3, prop4, propnum4, commander_id, tank_id from conf_reward";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///奖励组ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///奖励货币
	/// </summary>
	public int Money { get; set; }
	/// <summary>
	///银狮币
	/// </summary>
	public int Strategy_coin { get; set; }
	/// <summary>
	///军功
	/// </summary>
	public int Militaryexploit { get; set; }
	/// <summary>
	///金币
	/// </summary>
	public int Coin { get; set; }
	/// <summary>
	///公共经验
	/// </summary>
	public int Common_exp { get; set; }
	/// <summary>
	///主角经验
	/// </summary>
	public int Leader_exp { get; set; }
	/// <summary>
	///指挥官经验
	/// </summary>
	public int Commander_exp { get; set; }
	/// <summary>
	///战车经验
	/// </summary>
	public int Tank_exp { get; set; }
	/// <summary>
	///材料1id
	/// </summary>
	public int Material1 { get; set; }
	/// <summary>
	///材料1数量
	/// </summary>
	public int Materialnum1 { get; set; }
	/// <summary>
	///材料2id
	/// </summary>
	public int Material2 { get; set; }
	/// <summary>
	///材料2数量
	/// </summary>
	public int Materialnum2 { get; set; }
	/// <summary>
	///材料3id
	/// </summary>
	public int Material3 { get; set; }
	/// <summary>
	///材料3数量
	/// </summary>
	public int Materialnum3 { get; set; }
	/// <summary>
	///材料4id
	/// </summary>
	public int Material4 { get; set; }
	/// <summary>
	///材料4数量
	/// </summary>
	public int Materialnum4 { get; set; }
	/// <summary>
	///奖励道具id
	/// </summary>
	public int Prop1 { get; set; }
	/// <summary>
	///奖励道具数量
	/// </summary>
	public int Propnum1 { get; set; }
	/// <summary>
	///奖励道具id
	/// </summary>
	public int Prop2 { get; set; }
	/// <summary>
	///奖励道具数量
	/// </summary>
	public int Propnum2 { get; set; }
	/// <summary>
	///奖励道具id
	/// </summary>
	public int Prop3 { get; set; }
	/// <summary>
	///奖励道具数量
	/// </summary>
	public int Propnum3 { get; set; }
	/// <summary>
	///奖励道具id
	/// </summary>
	public int Prop4 { get; set; }
	/// <summary>
	///奖励道具数量
	/// </summary>
	public int Propnum4 { get; set; }
	/// <summary>
	///奖励指挥官id
	/// </summary>
	public int Commander_id { get; set; }
	/// <summary>
	///奖励坦克id
	/// </summary>
	public int Tank_id { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Reward module = new DB_Reward()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Money		 = reader.GetInt32(3),
					Strategy_coin		 = reader.GetInt32(4),
					Militaryexploit		 = reader.GetInt32(5),
					Coin		 = reader.GetInt32(6),
					Common_exp		 = reader.GetInt32(7),
					Leader_exp		 = reader.GetInt32(8),
					Commander_exp		 = reader.GetInt32(9),
					Tank_exp		 = reader.GetInt32(10),
					Material1		 = reader.GetInt32(11),
					Materialnum1		 = reader.GetInt32(12),
					Material2		 = reader.GetInt32(13),
					Materialnum2		 = reader.GetInt32(14),
					Material3		 = reader.GetInt32(15),
					Materialnum3		 = reader.GetInt32(16),
					Material4		 = reader.GetInt32(17),
					Materialnum4		 = reader.GetInt32(18),
					Prop1		 = reader.GetInt32(19),
					Propnum1		 = reader.GetInt32(20),
					Prop2		 = reader.GetInt32(21),
					Propnum2		 = reader.GetInt32(22),
					Prop3		 = reader.GetInt32(23),
					Propnum3		 = reader.GetInt32(24),
					Prop4		 = reader.GetInt32(25),
					Propnum4		 = reader.GetInt32(26),
					Commander_id		 = reader.GetInt32(27),
					Tank_id		 = reader.GetInt32(28),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
