using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Strategy_zone : IDB_BaseInt
{
	const string SQL = @"select _index, strategy_zone_id, strategy_zon_status, comment, limit_time, tax_diamonds, tax_money, tax_fuel, tax_strategy, tax_steel, tax_manganese, tax_tungsten, tax_zinc, tax_cycle, strategy, strategy_zone_title, strategy_zone_icon, strategy_zone_icon_my, strategy_zone_level, enemy_commander, first_reward, strategy_zone_map, strategy_show, arrow_show, strategy_zone_levelup, strategy_zone_core, reward_txt, strategy_stay, strategy_skil_show from conf_strategy_zone";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///战区id
	/// </summary>
	public int Strategy_zone_id { get; set; }
	/// <summary>
	///战区初始状态(2可进攻）
	/// </summary>
	public int Strategy_zon_status { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///战区进攻时间（单位：秒）
	/// </summary>
	public int Limit_time { get; set; }
	/// <summary>
	///税收钻石
	/// </summary>
	public int Tax_diamonds { get; set; }
	/// <summary>
	///税收游戏币
	/// </summary>
	public int Tax_money { get; set; }
	/// <summary>
	///税收燃油
	/// </summary>
	public int Tax_fuel { get; set; }
	/// <summary>
	///税收战略币
	/// </summary>
	public int Tax_strategy { get; set; }
	/// <summary>
	///税收钢1001（从conf_material_public.xlsx读）
	/// </summary>
	public int Tax_steel { get; set; }
	/// <summary>
	///税收锰1002从conf_material_public.xlsx读）
	/// </summary>
	public int Tax_manganese { get; set; }
	/// <summary>
	///税收钨1003从conf_material_public.xlsx读）
	/// </summary>
	public int Tax_tungsten { get; set; }
	/// <summary>
	///税收锌1004从conf_material_public.xlsx读）
	/// </summary>
	public int Tax_zinc { get; set; }
	/// <summary>
	///税收周期/秒
	/// </summary>
	public int Tax_cycle { get; set; }
	/// <summary>
	///战区内据点
	/// </summary>
	public string Strategy { get; set; }
	/// <summary>
	///标题-字库
	/// </summary>
	public string Strategy_zone_title { get; set; }
	/// <summary>
	///战区使用icon（敌占）
	/// </summary>
	public int Strategy_zone_icon { get; set; }
	/// <summary>
	///战区使用icon（己占）
	/// </summary>
	public int Strategy_zone_icon_my { get; set; }
	/// <summary>
	///推荐等级-字库
	/// </summary>
	public string Strategy_zone_level { get; set; }
	/// <summary>
	///敌方指挥官==核心要塞指挥官(conf_commander_attr_public.xlsx中id)
	/// </summary>
	public int Enemy_commander { get; set; }
	/// <summary>
	///首次通关奖励（假值：与战区核心要塞掉落相同）
	/// </summary>
	public int First_reward { get; set; }
	/// <summary>
	///战区使用地图conf_res_ui_sprite_client.xlsx中找28001&28002&28003共三张（1，2陆地，3沿海）
	/// </summary>
	public int Strategy_zone_map { get; set; }
	/// <summary>
	///据点显示
	/// </summary>
	public string Strategy_show { get; set; }
	/// <summary>
	///箭头显示
	/// </summary>
	public string Arrow_show { get; set; }
	/// <summary>
	///难度
	/// </summary>
	public int Strategy_zone_levelup { get; set; }
	/// <summary>
	///核心要塞名称
	/// </summary>
	public string Strategy_zone_core { get; set; }
	/// <summary>
	///首次通关奖励文字
	/// </summary>
	public string Reward_txt { get; set; }
	/// <summary>
	///战区位置
	/// </summary>
	public string Strategy_stay { get; set; }
	/// <summary>
	///战区场景技能状态icon显示（conconf_res_ui_sprite_client.xlsx中找id）
	/// </summary>
	public string Strategy_skil_show { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Strategy_zone module = new DB_Strategy_zone()
				{
					_index		 = reader.GetInt32(0),
					Strategy_zone_id		 = reader.GetInt32(1),
					Strategy_zon_status		 = reader.GetInt32(2),
					Comment		 = reader.GetString(3),
					Limit_time		 = reader.GetInt32(4),
					Tax_diamonds		 = reader.GetInt32(5),
					Tax_money		 = reader.GetInt32(6),
					Tax_fuel		 = reader.GetInt32(7),
					Tax_strategy		 = reader.GetInt32(8),
					Tax_steel		 = reader.GetInt32(9),
					Tax_manganese		 = reader.GetInt32(10),
					Tax_tungsten		 = reader.GetInt32(11),
					Tax_zinc		 = reader.GetInt32(12),
					Tax_cycle		 = reader.GetInt32(13),
					Strategy		 = reader.GetString(14),
					Strategy_zone_title		 = reader.GetString(15),
					Strategy_zone_icon		 = reader.GetInt32(16),
					Strategy_zone_icon_my		 = reader.GetInt32(17),
					Strategy_zone_level		 = reader.GetString(18),
					Enemy_commander		 = reader.GetInt32(19),
					First_reward		 = reader.GetInt32(20),
					Strategy_zone_map		 = reader.GetInt32(21),
					Strategy_show		 = reader.GetString(22),
					Arrow_show		 = reader.GetString(23),
					Strategy_zone_levelup		 = reader.GetInt32(24),
					Strategy_zone_core		 = reader.GetString(25),
					Reward_txt		 = reader.GetString(26),
					Strategy_stay		 = reader.GetString(27),
					Strategy_skil_show		 = reader.GetString(28),
				};
				tmp.Add(module.Strategy_zone_id, module);
			}
		});
		return tmp;
	}
}
