using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Strategy_researchcenter : IDB_BaseIntDouble
{
	const string SQL = @"select _index, type_id, index_list, type_txt, type_icon, comment, skill_id, skill_star, skill_limit_type, lv_limit, use_type, use_cost, skill_use_limit from conf_strategy_researchcenter";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///类型
	/// </summary>
	public int Type_id { get; set; }
	/// <summary>
	///优先级
	/// </summary>
	public int Index_list { get; set; }
	/// <summary>
	///类型文本
	/// </summary>
	public string Type_txt { get; set; }
	/// <summary>
	///类型icon（从UI表读取）
	/// </summary>
	public int Type_icon { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///技能id（从表conf_skill_info_public.xlsx中读取）
	/// </summary>
	public int Skill_id { get; set; }
	/// <summary>
	///技能初始等级
	/// </summary>
	public int Skill_star { get; set; }
	/// <summary>
	///解锁类型(1:研究中心等级限制。2：占领防线ID限制)
	/// </summary>
	public int Skill_limit_type { get; set; }
	/// <summary>
	///研究中心级限制数量
	/// </summary>
	public int Lv_limit { get; set; }
	/// <summary>
	///使用技能消耗货币类型（101 游戏币 124 战略大作战货币）
	/// </summary>
	public int Use_type { get; set; }
	/// <summary>
	///消耗货币数量
	/// </summary>
	public int Use_cost { get; set; }
	/// <summary>
	///技能使用限制(文本)
	/// </summary>
	public string Skill_use_limit { get; set; }

	static Dictionary<int, Dictionary<int, IDB_BaseIntDouble>> LoadDB()
	{
		Dictionary<int, Dictionary<int, IDB_BaseIntDouble>> tmp = new Dictionary<int, Dictionary<int, IDB_BaseIntDouble>>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Strategy_researchcenter module = new DB_Strategy_researchcenter()
				{
					_index		 = reader.GetInt32(0),
					Type_id		 = reader.GetInt32(1),
					Index_list		 = reader.GetInt32(2),
					Type_txt		 = reader.GetString(3),
					Type_icon		 = reader.GetInt32(4),
					Comment		 = reader.GetString(5),
					Skill_id		 = reader.GetInt32(6),
					Skill_star		 = reader.GetInt32(7),
					Skill_limit_type		 = reader.GetInt32(8),
					Lv_limit		 = reader.GetInt32(9),
					Use_type		 = reader.GetInt32(10),
					Use_cost		 = reader.GetInt32(11),
					Skill_use_limit		 = reader.GetString(12),
				};
				if (!tmp.ContainsKey(module.Type_id))
				{
					var tmpsub = new Dictionary<int, IDB_BaseIntDouble>();
					tmp.Add(module.Type_id, tmpsub);
				}
				tmp[module.Type_id].Add(module.Index_list, module);
			}
		});
		return tmp;
	}
}
