using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Strategy_zone_tax : IDB_BaseInt
{
	const string SQL = @"select _index, commander_level, tax_up from conf_strategy_zone_tax";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///驻守指挥官等级
	/// </summary>
	public int Commander_level { get; set; }
	/// <summary>
	///税收提升率
	/// </summary>
	public int Tax_up { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Strategy_zone_tax module = new DB_Strategy_zone_tax()
				{
					_index		 = reader.GetInt32(0),
					Commander_level		 = reader.GetInt32(1),
					Tax_up		 = reader.GetInt32(2),
				};
				tmp.Add(module.Commander_level, module);
			}
		});
		return tmp;
	}
}
