using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Skill_queue : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skill10, skill11, skill12, cd_time from conf_skill_queue";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///队列id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///战斗开始释放，每场战斗仅限一次
	/// </summary>
	public int Skill0 { get; set; }
	/// <summary>
	///循环开始的第一个技能，以后依次类推。本列数据中，0=普通攻击，1=车体技能，2=火炮技能，3=炮塔技能，4=引擎技能，5=底盘技能，6=火控技能。如果坦克技能队列存在某个技能，而对应的装备没有技能的话，到那个技能触发的时候用普通攻击替代。
	/// </summary>
	public int Skill1 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill2 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill3 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill4 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill5 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill6 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill7 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill8 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill9 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill10 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill11 { get; set; }
	/// <summary>
	///序列对应技能
	/// </summary>
	public int Skill12 { get; set; }
	/// <summary>
	///该序列对应的CD
	/// </summary>
	public float Cd_time { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Skill_queue module = new DB_Skill_queue()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Skill0		 = reader.GetInt32(3),
					Skill1		 = reader.GetInt32(4),
					Skill2		 = reader.GetInt32(5),
					Skill3		 = reader.GetInt32(6),
					Skill4		 = reader.GetInt32(7),
					Skill5		 = reader.GetInt32(8),
					Skill6		 = reader.GetInt32(9),
					Skill7		 = reader.GetInt32(10),
					Skill8		 = reader.GetInt32(11),
					Skill9		 = reader.GetInt32(12),
					Skill10		 = reader.GetInt32(13),
					Skill11		 = reader.GetInt32(14),
					Skill12		 = reader.GetInt32(15),
					Cd_time		 = reader.GetFloat(16),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
