using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Strategy_link : IDB_BaseInt
{
	const string SQL = @"select _index, strategy_id, linked_strategy_id from conf_strategy_link";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///据点id
	/// </summary>
	public int Strategy_id { get; set; }
	/// <summary>
	///可解锁据点id
	/// </summary>
	public string Linked_strategy_id { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Strategy_link module = new DB_Strategy_link()
				{
					_index		 = reader.GetInt32(0),
					Strategy_id		 = reader.GetInt32(1),
					Linked_strategy_id		 = reader.GetString(2),
				};
				tmp.Add(module.Strategy_id, module);
			}
		});
		return tmp;
	}
}
