using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Strategy_explore : IDB_BaseInt
{
	const string SQL = @"select _index, explore_id, explore_type, explore_title, speak1, change_content1, change_content2, change_content3, speak2, result1, speak5, speak3, result2, speak6, speak4, result3, speak7, strategy_battle1, strategy_battle2, reward1, reward2, reward3 from conf_strategy_explore";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///探索ID
	/// </summary>
	public int Explore_id { get; set; }
	/// <summary>
	///探索类型（1：代表主线。2代表随机）
	/// </summary>
	public int Explore_type { get; set; }
	/// <summary>
	///探索标题（字库key）
	/// </summary>
	public string Explore_title { get; set; }
	/// <summary>
	///前置对话引导conf_conversation_info_client表中找ID
	/// </summary>
	public int Speak1 { get; set; }
	/// <summary>
	///选项1
	/// </summary>
	public string Change_content1 { get; set; }
	/// <summary>
	///选项2
	/// </summary>
	public string Change_content2 { get; set; }
	/// <summary>
	///选项3
	/// </summary>
	public string Change_content3 { get; set; }
	/// <summary>
	///解锁对话1conf_conversation_info_client表中找ID
	/// </summary>
	public int Speak2 { get; set; }
	/// <summary>
	///结果1
	/// </summary>
	public string Result1 { get; set; }
	/// <summary>
	///后置对话引导conf_conversation_info_client表中找ID
	/// </summary>
	public int Speak5 { get; set; }
	/// <summary>
	///解锁对话2conf_conversation_info_client表中找ID
	/// </summary>
	public int Speak3 { get; set; }
	/// <summary>
	///结果2
	/// </summary>
	public string Result2 { get; set; }
	/// <summary>
	///后置对话引导conf_conversation_info_client表中找ID
	/// </summary>
	public int Speak6 { get; set; }
	/// <summary>
	///解锁对话3conf_conversation_info_client表中找ID
	/// </summary>
	public int Speak4 { get; set; }
	/// <summary>
	///结果3
	/// </summary>
	public string Result3 { get; set; }
	/// <summary>
	///后置对话引导conf_conversation_info_client表中找ID
	/// </summary>
	public int Speak7 { get; set; }
	/// <summary>
	///剧情战斗1，数据从conf_activities_battle_public取得
	/// </summary>
	public int Strategy_battle1 { get; set; }
	/// <summary>
	///剧情战斗2，数据从conf_activities_battle_public取得
	/// </summary>
	public int Strategy_battle2 { get; set; }
	/// <summary>
	///奖励组1：数据从conf_reward_public.xlsx中取
	/// </summary>
	public int Reward1 { get; set; }
	/// <summary>
	///奖励组2数据从conf_reward_public.xlsx中取
	/// </summary>
	public int Reward2 { get; set; }
	/// <summary>
	///奖励组3数据从conf_reward_public.xlsx中取
	/// </summary>
	public int Reward3 { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Strategy_explore module = new DB_Strategy_explore()
				{
					_index		 = reader.GetInt32(0),
					Explore_id		 = reader.GetInt32(1),
					Explore_type		 = reader.GetInt32(2),
					Explore_title		 = reader.GetString(3),
					Speak1		 = reader.GetInt32(4),
					Change_content1		 = reader.GetString(5),
					Change_content2		 = reader.GetString(6),
					Change_content3		 = reader.GetString(7),
					Speak2		 = reader.GetInt32(8),
					Result1		 = reader.GetString(9),
					Speak5		 = reader.GetInt32(10),
					Speak3		 = reader.GetInt32(11),
					Result2		 = reader.GetString(12),
					Speak6		 = reader.GetInt32(13),
					Speak4		 = reader.GetInt32(14),
					Result3		 = reader.GetString(15),
					Speak7		 = reader.GetInt32(16),
					Strategy_battle1		 = reader.GetInt32(17),
					Strategy_battle2		 = reader.GetInt32(18),
					Reward1		 = reader.GetInt32(19),
					Reward2		 = reader.GetInt32(20),
					Reward3		 = reader.GetInt32(21),
				};
				tmp.Add(module.Explore_id, module);
			}
		});
		return tmp;
	}
}
