using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Strategy_skill : IDB_BaseInt
{
	const string SQL = @"select _index, level, next_level, cost_type, cost_num, level_limit, level_limit_word from conf_strategy_skill";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///技能等级
	/// </summary>
	public int Level { get; set; }
	/// <summary>
	///技能下一等级
	/// </summary>
	public int Next_level { get; set; }
	/// <summary>
	///升级花费货币类型（101 游戏币 124 战略大作战货币）
	/// </summary>
	public int Cost_type { get; set; }
	/// <summary>
	///升级花费
	/// </summary>
	public int Cost_num { get; set; }
	/// <summary>
	///升级所需研究中心等级
	/// </summary>
	public int Level_limit { get; set; }
	/// <summary>
	///升级条件文本
	/// </summary>
	public string Level_limit_word { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Strategy_skill module = new DB_Strategy_skill()
				{
					_index		 = reader.GetInt32(0),
					Level		 = reader.GetInt32(1),
					Next_level		 = reader.GetInt32(2),
					Cost_type		 = reader.GetInt32(3),
					Cost_num		 = reader.GetInt32(4),
					Level_limit		 = reader.GetInt32(5),
					Level_limit_word		 = reader.GetString(6),
				};
				tmp.Add(module.Level, module);
			}
		});
		return tmp;
	}
}
