using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Strategy_random : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, battle_id, line, level_txt, random_icon from conf_strategy_random";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///野怪ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///战斗ID从
	/// </summary>
	public int Battle_id { get; set; }
	/// <summary>
	///所属防线
	/// </summary>
	public int Line { get; set; }
	/// <summary>
	///显示等级（字库）
	/// </summary>
	public string Level_txt { get; set; }
	/// <summary>
	///使用icon（从表conf_res_ui_sprite_client.xlsx找）
	/// </summary>
	public int Random_icon { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Strategy_random module = new DB_Strategy_random()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Battle_id		 = reader.GetInt32(3),
					Line		 = reader.GetInt32(4),
					Level_txt		 = reader.GetString(5),
					Random_icon		 = reader.GetInt32(6),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
