using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Strategy_line_attack : IDB_BaseInt
{
	const string SQL = @"select _index, id, level_down, level_up, strategy_battle, intrusion_time, hold_chance, sgainst_chance from conf_strategy_line_attack";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///入侵id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///玩家等级下限
	/// </summary>
	public int Level_down { get; set; }
	/// <summary>
	///玩家等级上限
	/// </summary>
	public int Level_up { get; set; }
	/// <summary>
	///入侵战斗(conf_activities_battle_public表中获得)
	/// </summary>
	public int Strategy_battle { get; set; }
	/// <summary>
	///入侵时间（单位：秒）
	/// </summary>
	public int Intrusion_time { get; set; }
	/// <summary>
	///占领状态触发几率
	/// </summary>
	public int Hold_chance { get; set; }
	/// <summary>
	///争夺中状态触发几率
	/// </summary>
	public int Sgainst_chance { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Strategy_line_attack module = new DB_Strategy_line_attack()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Level_down		 = reader.GetInt32(2),
					Level_up		 = reader.GetInt32(3),
					Strategy_battle		 = reader.GetInt32(4),
					Intrusion_time		 = reader.GetInt32(5),
					Hold_chance		 = reader.GetInt32(6),
					Sgainst_chance		 = reader.GetInt32(7),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
