using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Section : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, video, Unlock_battleID, Main_Title, Title1, Title2, Title3, Title4, Point1, Point2, Point3, Point4, icon from conf_section";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///位置编号
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///视频名称
	/// </summary>
	public string Video { get; set; }
	/// <summary>
	///对应关卡id
	/// </summary>
	public int Unlock_battleID { get; set; }
	/// <summary>
	///主标题
	/// </summary>
	public string Main_Title { get; set; }
	/// <summary>
	///标题1
	/// </summary>
	public string Title1 { get; set; }
	/// <summary>
	///标题2
	/// </summary>
	public string Title2 { get; set; }
	/// <summary>
	///标题3
	/// </summary>
	public string Title3 { get; set; }
	/// <summary>
	///标题4
	/// </summary>
	public string Title4 { get; set; }
	/// <summary>
	///内容1
	/// </summary>
	public string Point1 { get; set; }
	/// <summary>
	///内容2
	/// </summary>
	public string Point2 { get; set; }
	/// <summary>
	///内容3
	/// </summary>
	public string Point3 { get; set; }
	/// <summary>
	///内容4
	/// </summary>
	public string Point4 { get; set; }
	/// <summary>
	///图标
	/// </summary>
	public int Icon { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Section module = new DB_Section()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Video		 = reader.GetString(3),
					Unlock_battleID		 = reader.GetInt32(4),
					Main_Title		 = reader.GetString(5),
					Title1		 = reader.GetString(6),
					Title2		 = reader.GetString(7),
					Title3		 = reader.GetString(8),
					Title4		 = reader.GetString(9),
					Point1		 = reader.GetString(10),
					Point2		 = reader.GetString(11),
					Point3		 = reader.GetString(12),
					Point4		 = reader.GetString(13),
					Icon		 = reader.GetInt32(14),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
