using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Tank_attr : IDB_BaseInt
{
	const string SQL = @"select _index, id, tanktag, name, description, comment, rank, weight, series, country, init_star, rare, health, explosion_attack, pierce_attack, burning_attack, explosion_guard, pierce_guard, burning_guard, hit, volt, bang, bang_guard, puncture, parry, health_growth, explosion_attack_growth, pierce_attack_growth, burning_attack_growth, explosion_guard_growth, pierce_guard_growth, burning_guard_growth, strengthen_next_id, skill_queue, size, res_tank_id, icon, effects_group, skill_count, attack_skill_id, attack_skill_level, body_skill_id, body_skill_level, equip_init, texture, texture_uesable, level_rule_id, strengthen_rule_id, strengthen_level, quality_rule_id, resolve_rule, type, mark, hit_growth, volt_growth, bang_growth, bang_guard_growth, puncture_growth, parry_growth, move_speed, attack_distance, tactics_distance, attack_speed, target_logic, tactics, tactics_normal, tactics_attack, tactics_defend, fire_dist, stop_dist from conf_tank_attr";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///战车ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///车体ID
	/// </summary>
	public int Tanktag { get; set; }
	/// <summary>
	///战车名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///战车描述
	/// </summary>
	public string Description { get; set; }
	/// <summary>
	///战车备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///战车等级
	/// </summary>
	public int Rank { get; set; }
	/// <summary>
	///战车量级
	/// </summary>
	public int Weight { get; set; }
	/// <summary>
	///战车表现
	/// </summary>
	public int Series { get; set; }
	/// <summary>
	///战车国籍
	/// </summary>
	public int Country { get; set; }
	/// <summary>
	///初始星级
	/// </summary>
	public int Init_star { get; set; }
	/// <summary>
	///战车强化级别
	/// </summary>
	public int Rare { get; set; }
	/// <summary>
	///生命
	/// </summary>
	public float Health { get; set; }
	/// <summary>
	///爆炸伤害
	/// </summary>
	public float Explosion_attack { get; set; }
	/// <summary>
	///穿透伤害
	/// </summary>
	public float Pierce_attack { get; set; }
	/// <summary>
	///燃烧伤害
	/// </summary>
	public float Burning_attack { get; set; }
	/// <summary>
	///爆炸防御力
	/// </summary>
	public float Explosion_guard { get; set; }
	/// <summary>
	///穿透防御力
	/// </summary>
	public float Pierce_guard { get; set; }
	/// <summary>
	///燃烧防御力
	/// </summary>
	public float Burning_guard { get; set; }
	/// <summary>
	///命中
	/// </summary>
	public float Hit { get; set; }
	/// <summary>
	///闪避
	/// </summary>
	public float Volt { get; set; }
	/// <summary>
	///暴击
	/// </summary>
	public float Bang { get; set; }
	/// <summary>
	///暴防
	/// </summary>
	public float Bang_guard { get; set; }
	/// <summary>
	///穿深
	/// </summary>
	public float Puncture { get; set; }
	/// <summary>
	///装甲
	/// </summary>
	public float Parry { get; set; }
	/// <summary>
	///生命等级成长
	/// </summary>
	public float Health_growth { get; set; }
	/// <summary>
	///爆炸伤害等级成长
	/// </summary>
	public float Explosion_attack_growth { get; set; }
	/// <summary>
	///穿透伤害等级成长
	/// </summary>
	public float Pierce_attack_growth { get; set; }
	/// <summary>
	///燃烧伤害等级成长
	/// </summary>
	public float Burning_attack_growth { get; set; }
	/// <summary>
	///爆炸防御力等级成长
	/// </summary>
	public float Explosion_guard_growth { get; set; }
	/// <summary>
	///穿透防御力等级成长
	/// </summary>
	public float Pierce_guard_growth { get; set; }
	/// <summary>
	///燃烧防御力等级成长
	/// </summary>
	public float Burning_guard_growth { get; set; }
	/// <summary>
	///强化后ID
	/// </summary>
	public int Strengthen_next_id { get; set; }
	/// <summary>
	///技能队列
	/// </summary>
	public int Skill_queue { get; set; }
	/// <summary>
	///大小
	/// </summary>
	public int Size { get; set; }
	/// <summary>
	///模型
	/// </summary>
	public int Res_tank_id { get; set; }
	/// <summary>
	///图标
	/// </summary>
	public int Icon { get; set; }
	/// <summary>
	///特效组
	/// </summary>
	public int Effects_group { get; set; }
	/// <summary>
	///技能数量
	/// </summary>
	public int Skill_count { get; set; }
	/// <summary>
	///普攻
	/// </summary>
	public int Attack_skill_id { get; set; }
	/// <summary>
	///普攻等级
	/// </summary>
	public int Attack_skill_level { get; set; }
	/// <summary>
	///车体技能
	/// </summary>
	public int Body_skill_id { get; set; }
	/// <summary>
	///车体技能等级
	/// </summary>
	public int Body_skill_level { get; set; }
	/// <summary>
	///默认装备组ID
	/// </summary>
	public int Equip_init { get; set; }
	/// <summary>
	///贴图
	/// </summary>
	public int Texture { get; set; }
	/// <summary>
	///可用涂装
	/// </summary>
	public string Texture_uesable { get; set; }
	/// <summary>
	///升级消耗规则
	/// </summary>
	public int Level_rule_id { get; set; }
	/// <summary>
	///强化消耗规则
	/// </summary>
	public int Strengthen_rule_id { get; set; }
	/// <summary>
	///强化所需等级
	/// </summary>
	public int Strengthen_level { get; set; }
	/// <summary>
	///升星消耗规则
	/// </summary>
	public int Quality_rule_id { get; set; }
	/// <summary>
	///分解规则
	/// </summary>
	public int Resolve_rule { get; set; }
	/// <summary>
	///战车类别
	/// </summary>
	public int Type { get; set; }
	/// <summary>
	///标识
	/// </summary>
	public int Mark { get; set; }
	/// <summary>
	///命中等级成长
	/// </summary>
	public float Hit_growth { get; set; }
	/// <summary>
	///闪避等级成长
	/// </summary>
	public float Volt_growth { get; set; }
	/// <summary>
	///暴击等级成长
	/// </summary>
	public float Bang_growth { get; set; }
	/// <summary>
	///暴防等级成长
	/// </summary>
	public float Bang_guard_growth { get; set; }
	/// <summary>
	///穿深等级成长
	/// </summary>
	public float Puncture_growth { get; set; }
	/// <summary>
	///格挡等级成长
	/// </summary>
	public float Parry_growth { get; set; }
	/// <summary>
	///移动速度
	/// </summary>
	public int Move_speed { get; set; }
	/// <summary>
	///攻击距离
	/// </summary>
	public int Attack_distance { get; set; }
	/// <summary>
	///停止距离
	/// </summary>
	public int Tactics_distance { get; set; }
	/// <summary>
	///攻击速度
	/// </summary>
	public int Attack_speed { get; set; }
	/// <summary>
	///目标选择逻辑
	/// </summary>
	public int Target_logic { get; set; }
	/// <summary>
	///策略类型
	/// </summary>
	public int Tactics { get; set; }
	/// <summary>
	///普通战术策略
	/// </summary>
	public int Tactics_normal { get; set; }
	/// <summary>
	///攻击战术策略
	/// </summary>
	public int Tactics_attack { get; set; }
	/// <summary>
	///防守战术策略
	/// </summary>
	public int Tactics_defend { get; set; }
	/// <summary>
	///开火距离
	/// </summary>
	public int Fire_dist { get; set; }
	/// <summary>
	///停止距离
	/// </summary>
	public int Stop_dist { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Tank_attr module = new DB_Tank_attr()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Tanktag		 = reader.GetInt32(2),
					Name		 = reader.GetString(3),
					Description		 = reader.GetString(4),
					Comment		 = reader.GetString(5),
					Rank		 = reader.GetInt32(6),
					Weight		 = reader.GetInt32(7),
					Series		 = reader.GetInt32(8),
					Country		 = reader.GetInt32(9),
					Init_star		 = reader.GetInt32(10),
					Rare		 = reader.GetInt32(11),
					Health		 = reader.GetFloat(12),
					Explosion_attack		 = reader.GetFloat(13),
					Pierce_attack		 = reader.GetFloat(14),
					Burning_attack		 = reader.GetFloat(15),
					Explosion_guard		 = reader.GetFloat(16),
					Pierce_guard		 = reader.GetFloat(17),
					Burning_guard		 = reader.GetFloat(18),
					Hit		 = reader.GetFloat(19),
					Volt		 = reader.GetFloat(20),
					Bang		 = reader.GetFloat(21),
					Bang_guard		 = reader.GetFloat(22),
					Puncture		 = reader.GetFloat(23),
					Parry		 = reader.GetFloat(24),
					Health_growth		 = reader.GetFloat(25),
					Explosion_attack_growth		 = reader.GetFloat(26),
					Pierce_attack_growth		 = reader.GetFloat(27),
					Burning_attack_growth		 = reader.GetFloat(28),
					Explosion_guard_growth		 = reader.GetFloat(29),
					Pierce_guard_growth		 = reader.GetFloat(30),
					Burning_guard_growth		 = reader.GetFloat(31),
					Strengthen_next_id		 = reader.GetInt32(32),
					Skill_queue		 = reader.GetInt32(33),
					Size		 = reader.GetInt32(34),
					Res_tank_id		 = reader.GetInt32(35),
					Icon		 = reader.GetInt32(36),
					Effects_group		 = reader.GetInt32(37),
					Skill_count		 = reader.GetInt32(38),
					Attack_skill_id		 = reader.GetInt32(39),
					Attack_skill_level		 = reader.GetInt32(40),
					Body_skill_id		 = reader.GetInt32(41),
					Body_skill_level		 = reader.GetInt32(42),
					Equip_init		 = reader.GetInt32(43),
					Texture		 = reader.GetInt32(44),
					Texture_uesable		 = reader.GetString(45),
					Level_rule_id		 = reader.GetInt32(46),
					Strengthen_rule_id		 = reader.GetInt32(47),
					Strengthen_level		 = reader.GetInt32(48),
					Quality_rule_id		 = reader.GetInt32(49),
					Resolve_rule		 = reader.GetInt32(50),
					Type		 = reader.GetInt32(51),
					Mark		 = reader.GetInt32(52),
					Hit_growth		 = reader.GetFloat(53),
					Volt_growth		 = reader.GetFloat(54),
					Bang_growth		 = reader.GetFloat(55),
					Bang_guard_growth		 = reader.GetFloat(56),
					Puncture_growth		 = reader.GetFloat(57),
					Parry_growth		 = reader.GetFloat(58),
					Move_speed		 = reader.GetInt32(59),
					Attack_distance		 = reader.GetInt32(60),
					Tactics_distance		 = reader.GetInt32(61),
					Attack_speed		 = reader.GetInt32(62),
					Target_logic		 = reader.GetInt32(63),
					Tactics		 = reader.GetInt32(64),
					Tactics_normal		 = reader.GetInt32(65),
					Tactics_attack		 = reader.GetInt32(66),
					Tactics_defend		 = reader.GetInt32(67),
					Fire_dist		 = reader.GetInt32(68),
					Stop_dist		 = reader.GetInt32(69),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
