using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Tank_quality_rule : IDB_BaseInt
{
	const string SQL = @"select _index, quality_rule_id, money_need, gold_need, material1_id, material1_cost, material2_id, material2_cost, material3_id, material3_cost, prop1_id, prop1_cost, prop2_id, prop2_cost, prop3_id, prop3_cost from conf_tank_quality_rule";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///升星规则ID
	/// </summary>
	public int Quality_rule_id { get; set; }
	/// <summary>
	///升星消耗的游戏币
	/// </summary>
	public int Money_need { get; set; }
	/// <summary>
	///升星消耗的金币
	/// </summary>
	public int Gold_need { get; set; }
	/// <summary>
	///升星消耗材料1ID
	/// </summary>
	public int Material1_id { get; set; }
	/// <summary>
	///升星消耗材料1数量
	/// </summary>
	public int Material1_cost { get; set; }
	/// <summary>
	///升星消耗材料2ID
	/// </summary>
	public int Material2_id { get; set; }
	/// <summary>
	///升星消耗材料2数量
	/// </summary>
	public int Material2_cost { get; set; }
	/// <summary>
	///升星消耗材料3ID
	/// </summary>
	public int Material3_id { get; set; }
	/// <summary>
	///升星消耗材料3数量
	/// </summary>
	public int Material3_cost { get; set; }
	/// <summary>
	///升星道具1ID
	/// </summary>
	public int Prop1_id { get; set; }
	/// <summary>
	///升星消耗道具1数量
	/// </summary>
	public int Prop1_cost { get; set; }
	/// <summary>
	///升星消耗道具2ID
	/// </summary>
	public int Prop2_id { get; set; }
	/// <summary>
	///升星消耗道具2数量
	/// </summary>
	public int Prop2_cost { get; set; }
	/// <summary>
	///升星消耗道具3ID
	/// </summary>
	public int Prop3_id { get; set; }
	/// <summary>
	///升星消耗道具3数量
	/// </summary>
	public int Prop3_cost { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Tank_quality_rule module = new DB_Tank_quality_rule()
				{
					_index		 = reader.GetInt32(0),
					Quality_rule_id		 = reader.GetInt32(1),
					Money_need		 = reader.GetInt32(2),
					Gold_need		 = reader.GetInt32(3),
					Material1_id		 = reader.GetInt32(4),
					Material1_cost		 = reader.GetInt32(5),
					Material2_id		 = reader.GetInt32(6),
					Material2_cost		 = reader.GetInt32(7),
					Material3_id		 = reader.GetInt32(8),
					Material3_cost		 = reader.GetInt32(9),
					Prop1_id		 = reader.GetInt32(10),
					Prop1_cost		 = reader.GetInt32(11),
					Prop2_id		 = reader.GetInt32(12),
					Prop2_cost		 = reader.GetInt32(13),
					Prop3_id		 = reader.GetInt32(14),
					Prop3_cost		 = reader.GetInt32(15),
				};
				tmp.Add(module.Quality_rule_id, module);
			}
		});
		return tmp;
	}
}
