using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Tank_resolve_rule : IDB_BaseInt
{
	const string SQL = @"select _index, id, get_prop_id, get_prop_num_star1, get_prop_num_star2, get_prop_num_star3, get_prop_num_star4, get_prop_num_star5, material1_id, material1_get, material2_id, material2_get, material3_id, material3_get, material4_id, material4_get from conf_tank_resolve_rule";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///分解规则ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///拆解获得道具id
	/// </summary>
	public int Get_prop_id { get; set; }
	/// <summary>
	///1星坦克拆解获得的道具数量
	/// </summary>
	public int Get_prop_num_star1 { get; set; }
	/// <summary>
	///2星坦克拆解获得的道具数量
	/// </summary>
	public int Get_prop_num_star2 { get; set; }
	/// <summary>
	///3星坦克拆解获得的道具数量
	/// </summary>
	public int Get_prop_num_star3 { get; set; }
	/// <summary>
	///4星坦克拆解获得的道具数量
	/// </summary>
	public int Get_prop_num_star4 { get; set; }
	/// <summary>
	///5星坦克拆解获得的道具数量
	/// </summary>
	public int Get_prop_num_star5 { get; set; }
	/// <summary>
	///基础分解材料1类型
	/// </summary>
	public int Material1_id { get; set; }
	/// <summary>
	///基础分解材料1数量
	/// </summary>
	public int Material1_get { get; set; }
	/// <summary>
	///基础分解材料2类型
	/// </summary>
	public int Material2_id { get; set; }
	/// <summary>
	///基础分解材料2数量
	/// </summary>
	public int Material2_get { get; set; }
	/// <summary>
	///基础分解材料3类型
	/// </summary>
	public int Material3_id { get; set; }
	/// <summary>
	///基础分解材料3数量
	/// </summary>
	public int Material3_get { get; set; }
	/// <summary>
	///基础分解材料4类型
	/// </summary>
	public int Material4_id { get; set; }
	/// <summary>
	///基础分解材料4数量
	/// </summary>
	public int Material4_get { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Tank_resolve_rule module = new DB_Tank_resolve_rule()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Get_prop_id		 = reader.GetInt32(2),
					Get_prop_num_star1		 = reader.GetInt32(3),
					Get_prop_num_star2		 = reader.GetInt32(4),
					Get_prop_num_star3		 = reader.GetInt32(5),
					Get_prop_num_star4		 = reader.GetInt32(6),
					Get_prop_num_star5		 = reader.GetInt32(7),
					Material1_id		 = reader.GetInt32(8),
					Material1_get		 = reader.GetInt32(9),
					Material2_id		 = reader.GetInt32(10),
					Material2_get		 = reader.GetInt32(11),
					Material3_id		 = reader.GetInt32(12),
					Material3_get		 = reader.GetInt32(13),
					Material4_id		 = reader.GetInt32(14),
					Material4_get		 = reader.GetInt32(15),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
