using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Tank_texture : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, name, description, texture_path, texture, detailmapk, textureicon, unlockcondition, unlockid, unlocknum, attr, attrvalue, lasttime from conf_tank_texture";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///涂装id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///涂装名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///涂装描述
	/// </summary>
	public string Description { get; set; }
	/// <summary>
	///涂装文件路径
	/// </summary>
	public string Texture_path { get; set; }
	/// <summary>
	///涂装文件名
	/// </summary>
	public string Texture { get; set; }
	/// <summary>
	///是否启用DetailMapK，0=否，1=是，我也不知道这是啥，问美术
	/// </summary>
	public int Detailmapk { get; set; }
	/// <summary>
	///涂装图标
	/// </summary>
	public int Textureicon { get; set; }
	/// <summary>
	///获得条件，-1为默认可使用，1为消耗道具获得，2为钻石购买
	/// </summary>
	public int Unlockcondition { get; set; }
	/// <summary>
	///当条件为1时，这一列为prop id，条件为2时，这一列为货币id
	/// </summary>
	public int Unlockid { get; set; }
	/// <summary>
	///道具或货币数量
	/// </summary>
	public int Unlocknum { get; set; }
	/// <summary>
	///涂装附加的属性，-1为无属性
	/// </summary>
	public int Attr { get; set; }
	/// <summary>
	///附加的属性值
	/// </summary>
	public int Attrvalue { get; set; }
	/// <summary>
	///涂装持续时间，-1为永久获得，单位秒
	/// </summary>
	public int Lasttime { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Tank_texture module = new DB_Tank_texture()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Name		 = reader.GetString(3),
					Description		 = reader.GetString(4),
					Texture_path		 = reader.GetString(5),
					Texture		 = reader.GetString(6),
					Detailmapk		 = reader.GetInt32(7),
					Textureicon		 = reader.GetInt32(8),
					Unlockcondition		 = reader.GetInt32(9),
					Unlockid		 = reader.GetInt32(10),
					Unlocknum		 = reader.GetInt32(11),
					Attr		 = reader.GetInt32(12),
					Attrvalue		 = reader.GetInt32(13),
					Lasttime		 = reader.GetInt32(14),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
