using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Tacmission_event : IDB_BaseInt
{
	const string SQL = @"select _index, Id, comment, rank, failreward, sucessreward, time, commanderskill, skillnotfit, skillfit, tanktype0, notfittanktype0, fittanktype0, tanktype1, notfittanktype1, fittanktype1, tanktype2, notfittanktype2, fittanktype2, tanktype3, notfittanktype3, fittanktype3, tanktype4, notfittanktype4, fittanktype4 from conf_tacmission_event";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///任务id
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///任务品质
	/// </summary>
	public int Rank { get; set; }
	/// <summary>
	///失败任务奖励
	/// </summary>
	public int Failreward { get; set; }
	/// <summary>
	///成功
	/// </summary>
	public int Sucessreward { get; set; }
	/// <summary>
	///任务时间
	/// </summary>
	public int Time { get; set; }
	/// <summary>
	///需求指挥官技能
	/// </summary>
	public int Commanderskill { get; set; }
	/// <summary>
	///无技能成功率
	/// </summary>
	public int Skillnotfit { get; set; }
	/// <summary>
	///有技能成功率
	/// </summary>
	public int Skillfit { get; set; }
	/// <summary>
	///需求坦克1类型
	/// </summary>
	public int Tanktype0 { get; set; }
	/// <summary>
	///坦克1不匹配
	/// </summary>
	public int Notfittanktype0 { get; set; }
	/// <summary>
	///坦克1匹配
	/// </summary>
	public int Fittanktype0 { get; set; }
	/// <summary>
	///需求坦克2类型
	/// </summary>
	public int Tanktype1 { get; set; }
	/// <summary>
	///坦克2不匹配
	/// </summary>
	public int Notfittanktype1 { get; set; }
	/// <summary>
	///坦克2匹配
	/// </summary>
	public int Fittanktype1 { get; set; }
	/// <summary>
	///需求坦克3类型
	/// </summary>
	public int Tanktype2 { get; set; }
	/// <summary>
	///坦克3不匹配
	/// </summary>
	public int Notfittanktype2 { get; set; }
	/// <summary>
	///坦克3匹配
	/// </summary>
	public int Fittanktype2 { get; set; }
	/// <summary>
	///需求坦克4类型
	/// </summary>
	public int Tanktype3 { get; set; }
	/// <summary>
	///坦克4不匹配
	/// </summary>
	public int Notfittanktype3 { get; set; }
	/// <summary>
	///坦克4匹配
	/// </summary>
	public int Fittanktype3 { get; set; }
	/// <summary>
	///需求坦克5类型
	/// </summary>
	public int Tanktype4 { get; set; }
	/// <summary>
	///坦克5不匹配
	/// </summary>
	public int Notfittanktype4 { get; set; }
	/// <summary>
	///坦克5匹配
	/// </summary>
	public int Fittanktype4 { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Tacmission_event module = new DB_Tacmission_event()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Rank		 = reader.GetInt32(3),
					Failreward		 = reader.GetInt32(4),
					Sucessreward		 = reader.GetInt32(5),
					Time		 = reader.GetInt32(6),
					Commanderskill		 = reader.GetInt32(7),
					Skillnotfit		 = reader.GetInt32(8),
					Skillfit		 = reader.GetInt32(9),
					Tanktype0		 = reader.GetInt32(10),
					Notfittanktype0		 = reader.GetInt32(11),
					Fittanktype0		 = reader.GetInt32(12),
					Tanktype1		 = reader.GetInt32(13),
					Notfittanktype1		 = reader.GetInt32(14),
					Fittanktype1		 = reader.GetInt32(15),
					Tanktype2		 = reader.GetInt32(16),
					Notfittanktype2		 = reader.GetInt32(17),
					Fittanktype2		 = reader.GetInt32(18),
					Tanktype3		 = reader.GetInt32(19),
					Notfittanktype3		 = reader.GetInt32(20),
					Fittanktype3		 = reader.GetInt32(21),
					Tanktype4		 = reader.GetInt32(22),
					Notfittanktype4		 = reader.GetInt32(23),
					Fittanktype4		 = reader.GetInt32(24),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
