using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Tank_target_logic : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, prop_series1, prop_series2, prop_series3, prop_series4, prop_series5 from conf_tank_target_logic";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///逻辑ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///轻坦权重
	/// </summary>
	public int Prop_series1 { get; set; }
	/// <summary>
	///中坦权重
	/// </summary>
	public int Prop_series2 { get; set; }
	/// <summary>
	///重坦权重
	/// </summary>
	public int Prop_series3 { get; set; }
	/// <summary>
	///反坦权重
	/// </summary>
	public int Prop_series4 { get; set; }
	/// <summary>
	///火炮权重
	/// </summary>
	public int Prop_series5 { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Tank_target_logic module = new DB_Tank_target_logic()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Prop_series1		 = reader.GetInt32(3),
					Prop_series2		 = reader.GetInt32(4),
					Prop_series3		 = reader.GetInt32(5),
					Prop_series4		 = reader.GetInt32(6),
					Prop_series5		 = reader.GetInt32(7),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
