using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Tank_init_introduction : IDB_BaseInt
{
	const string SQL = @"select _index, id, name, comment, ui_defence, ui_power, ui_load, ui_maneuver, ui_description from conf_tank_init_introduction";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///战车ID
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///战车名称
	/// </summary>
	public string Name { get; set; }
	/// <summary>
	///战车备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///面板属性防护
	/// </summary>
	public int Ui_defence { get; set; }
	/// <summary>
	///面板属性火力
	/// </summary>
	public int Ui_power { get; set; }
	/// <summary>
	///面板属性承载
	/// </summary>
	public int Ui_load { get; set; }
	/// <summary>
	///面板属性机动
	/// </summary>
	public int Ui_maneuver { get; set; }
	/// <summary>
	///背景介绍
	/// </summary>
	public string Ui_description { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Tank_init_introduction module = new DB_Tank_init_introduction()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
					Comment		 = reader.GetString(3),
					Ui_defence		 = reader.GetInt32(4),
					Ui_power		 = reader.GetInt32(5),
					Ui_load		 = reader.GetInt32(6),
					Ui_maneuver		 = reader.GetInt32(7),
					Ui_description		 = reader.GetString(8),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
