using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Text_specification : IDB_BaseInt
{
	const string SQL = @"select _index, id, type, color, bold, tilt, transparency from conf_text_specification";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///规范名称
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///字号
	/// </summary>
	public int Type { get; set; }
	/// <summary>
	///颜色
	/// </summary>
	public string Color { get; set; }
	/// <summary>
	///加粗
	/// </summary>
	public int Bold { get; set; }
	/// <summary>
	///倾斜
	/// </summary>
	public int Tilt { get; set; }
	/// <summary>
	///透明度
	/// </summary>
	public int Transparency { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Text_specification module = new DB_Text_specification()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Type		 = reader.GetInt32(2),
					Color		 = reader.GetString(3),
					Bold		 = reader.GetInt32(4),
					Tilt		 = reader.GetInt32(5),
					Transparency		 = reader.GetInt32(6),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
