using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Tank_equip_place : IDB_BaseInt
{
	const string SQL = @"select _index, place, name from conf_tank_equip_place";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///装备位
	/// </summary>
	public int Place { get; set; }
	/// <summary>
	///名称
	/// </summary>
	public string Name { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Tank_equip_place module = new DB_Tank_equip_place()
				{
					_index		 = reader.GetInt32(0),
					Place		 = reader.GetInt32(1),
					Name		 = reader.GetString(2),
				};
				tmp.Add(module.Place, module);
			}
		});
		return tmp;
	}
}
