using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Vip_buy : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, type, times, vip_request, cost_type, cost_num, get_num from conf_vip_buy";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///值定义为type*1000+times
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///购买类型定义，内容与开发备注相同【10已被占用，在其他表】
	/// </summary>
	public int Type { get; set; }
	/// <summary>
	///购买次数
	/// </summary>
	public int Times { get; set; }
	/// <summary>
	///需求vip等级，-1为无vip等级需求
	/// </summary>
	public int Vip_request { get; set; }
	/// <summary>
	///需求的货币类型，1=钻石，2=游戏币，其他待补充
	/// </summary>
	public int Cost_type { get; set; }
	/// <summary>
	///消耗货币的数量
	/// </summary>
	public int Cost_num { get; set; }
	/// <summary>
	///获得物的数量
	/// </summary>
	public int Get_num { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Vip_buy module = new DB_Vip_buy()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Type		 = reader.GetInt32(3),
					Times		 = reader.GetInt32(4),
					Vip_request		 = reader.GetInt32(5),
					Cost_type		 = reader.GetInt32(6),
					Cost_num		 = reader.GetInt32(7),
					Get_num		 = reader.GetInt32(8),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
