using System.Collections.Generic; 

/// <summary>
/// THIS SOURCE CODE WAS AUTO-GENERATED BY TOOL, DO NOT MODIFY IT!
/// </summary>
public class DB_Vipinfomation : IDB_BaseInt
{
	const string SQL = @"select _index, id, comment, recharge, vipreward, rewardvalue, rewarddescription, vipdescription1, vipdescription2, vipdescription3, vipdescription4, vipdescription5, vipdescription6, vipdescription7, vipdescription8, vipdescription9, vipdescription10, vipdescription11, vipdescription12, vipdescription13, vipdescription14, vipdescription15, vipdescription16 from conf_vipinfomation";

	/// <summary>
	///序号
	/// </summary>
	public int _index { get; set; }
	/// <summary>
	///vip等级
	/// </summary>
	public int Id { get; set; }
	/// <summary>
	///开发备注
	/// </summary>
	public string Comment { get; set; }
	/// <summary>
	///vip经验值
	/// </summary>
	public int Recharge { get; set; }
	/// <summary>
	///vip礼包id（读reward表）
	/// </summary>
	public int Vipreward { get; set; }
	/// <summary>
	///vip礼包价值
	/// </summary>
	public int Rewardvalue { get; set; }
	/// <summary>
	///领取奖励说明
	/// </summary>
	public string Rewarddescription { get; set; }
	/// <summary>
	///vip特权描述1
	/// </summary>
	public string Vipdescription1 { get; set; }
	/// <summary>
	///vip特权描述2
	/// </summary>
	public string Vipdescription2 { get; set; }
	/// <summary>
	///vip特权描述3
	/// </summary>
	public string Vipdescription3 { get; set; }
	/// <summary>
	///vip特权描述4
	/// </summary>
	public string Vipdescription4 { get; set; }
	/// <summary>
	///vip特权描述5
	/// </summary>
	public string Vipdescription5 { get; set; }
	/// <summary>
	///vip特权描述6
	/// </summary>
	public string Vipdescription6 { get; set; }
	/// <summary>
	///vip特权描述7
	/// </summary>
	public string Vipdescription7 { get; set; }
	/// <summary>
	///vip特权描述8
	/// </summary>
	public string Vipdescription8 { get; set; }
	/// <summary>
	///vip特权描述9
	/// </summary>
	public string Vipdescription9 { get; set; }
	/// <summary>
	///vip特权描述10
	/// </summary>
	public string Vipdescription10 { get; set; }
	/// <summary>
	///vip特权描述11
	/// </summary>
	public string Vipdescription11 { get; set; }
	/// <summary>
	///vip特权描述12
	/// </summary>
	public string Vipdescription12 { get; set; }
	/// <summary>
	///vip特权描述13
	/// </summary>
	public string Vipdescription13 { get; set; }
	/// <summary>
	///vip特权描述14
	/// </summary>
	public string Vipdescription14 { get; set; }
	/// <summary>
	///vip特权描述15
	/// </summary>
	public string Vipdescription15 { get; set; }
	/// <summary>
	///vip特权描述16
	/// </summary>
	public string Vipdescription16 { get; set; }

	static Dictionary<int, IDB_BaseInt> LoadDB()
	{
		Dictionary<int, IDB_BaseInt> tmp = new Dictionary<int, IDB_BaseInt>();
		DBHelper.Instance.Query(SQL, (reader) =>
		{
			if (reader == null) return;

			while (reader.Read())
			{
				DB_Vipinfomation module = new DB_Vipinfomation()
				{
					_index		 = reader.GetInt32(0),
					Id		 = reader.GetInt32(1),
					Comment		 = reader.GetString(2),
					Recharge		 = reader.GetInt32(3),
					Vipreward		 = reader.GetInt32(4),
					Rewardvalue		 = reader.GetInt32(5),
					Rewarddescription		 = reader.GetString(6),
					Vipdescription1		 = reader.GetString(7),
					Vipdescription2		 = reader.GetString(8),
					Vipdescription3		 = reader.GetString(9),
					Vipdescription4		 = reader.GetString(10),
					Vipdescription5		 = reader.GetString(11),
					Vipdescription6		 = reader.GetString(12),
					Vipdescription7		 = reader.GetString(13),
					Vipdescription8		 = reader.GetString(14),
					Vipdescription9		 = reader.GetString(15),
					Vipdescription10		 = reader.GetString(16),
					Vipdescription11		 = reader.GetString(17),
					Vipdescription12		 = reader.GetString(18),
					Vipdescription13		 = reader.GetString(19),
					Vipdescription14		 = reader.GetString(20),
					Vipdescription15		 = reader.GetString(21),
					Vipdescription16		 = reader.GetString(22),
				};
				tmp.Add(module.Id, module);
			}
		});
		return tmp;
	}
}
